debugging

diff --git a/build-steps.d/1100_prepare-build-machine b/build-steps.d/1100_prepare-build-machine
--- a/build-steps.d/1100_prepare-build-machine
+++ b/build-steps.d/1100_prepare-build-machine
@@ -232,17 +232,22 @@ prepare-build-machine() {
    ## Debugging.
    cat /usr/sbin/policy-rc.d || true
 
-   ## Ensure, that haveged is functional on travis-ci machines.
-   service haveged restart
-   service haveged start
-   ## Fails on travis-ci machines?!
-   service haveged status || true
+   if [ "$CI" = "true" ]; then
+      ## Ensure, that haveged is functional on travis-ci machines.
+      service haveged restart
+      service haveged start
+      ## Fails on travis-ci machines?!
+      service haveged status || true
 
-   ## Debugging.
-   /etc/init.d/haveged restart || true
-   /etc/init.d/haveged start || true
-   ## Fails on travis-ci machines?!
-   /etc/init.d/haveged status || true
+      ## Debugging.
+      /etc/init.d/haveged restart || true
+      /etc/init.d/haveged start || true
+      ## Fails on travis-ci machines?!
+      /etc/init.d/haveged status || true
+   else
+      ## Debugging.
+      service haveged status
+   fi
 
    ## Trying to work around a Travis CI specific build error while running grml-debootstrap.
    ##
