Revert "fix"
This reverts commit 97e25e1c4d5e743f29ed9d44bd910067fff30a64.

diff --git a/build-steps.d/1100_prepare-build-machine b/build-steps.d/1100_prepare-build-machine
--- a/build-steps.d/1100_prepare-build-machine
+++ b/build-steps.d/1100_prepare-build-machine
@@ -260,13 +260,29 @@ Please delete Whonix's source code folder and get it again as user, not root!${r
       ## - for creating VirtualBox VM images
       ##      virtualbox
       ## - required for mounting vdi images
-      ##      libguestfs-tools (not installed here, but below)
+      ##      libguestfs-tools
+      ##      guestmount (wheezy only)
       apt-get $apt_timeout_opts $apt_unattended_opts --yes install \
          qemu-utils \
          grml-debootstrap \
          parted \
          kpartx \
-         mksh
+         mksh \
+         libguestfs-tools
+
+      if [ "$whonix_build_on_operating_system" = "ubuntu" ]; then
+         ## Hack for Ubuntu 12.04 Precise Pangolin / Travis CI.
+         true
+      else
+         ## Hack for Debian Wheezy.
+         ## guestmount has been merged into libguestfs-tools in Debian.
+         ## || true because this would fail on Debian Jessie.
+         apt-get $apt_timeout_opts $apt_unattended_opts --yes install guestmount || true
+      fi
+
+      ## Sanity test.
+      command -v guestmount >/dev/null
+      command -v guestunmount >/dev/null
 
       #######################################################################
       ## Build Dependencies for creating VirtualBox Images (.vdi and .ova) #
@@ -293,15 +309,10 @@ Please delete Whonix's source code folder and get it again as user, not root!${r
 
    ## Check if libguestfs-tools is installed.
    ## (Build Dependency for Whonix Build Script for creating .deb packages.)
-
-   #local dpkg_exit_code
-   #dpkg_exit_code="0"
-   #dpkg-query -Wf '${db:Status-abbrev}' "libguestfs-tools" 2>/dev/null | grep -q '^i' || { dpkg_exit_code="$?" ; true; };
-   #if [ ! "$dpkg_exit_code" = "0" ]; then
-
-   local command_v_return="0"
-   command -v guestunmount >/dev/null || { command_v_return="$?" ; true; };
-   if [ "$command_v_return" = "0" ]; then
+   local dpkg_exit_code
+   dpkg_exit_code="0"
+   dpkg-query -Wf '${db:Status-abbrev}' "libguestfs-tools" 2>/dev/null | grep -q '^i' || { dpkg_exit_code="$?" ; true; };
+   if [ ! "$dpkg_exit_code" = "0" ]; then
       if [ "$BARE_METAL" = "1" ]; then
          true "INFO: BARE_METAL is $BARE_METAL, installation of libguestfs-tools not required, ok."
       else
@@ -342,21 +353,7 @@ Please delete Whonix's source code folder and get it again as user, not root!${r
          install \
          config-package-dev/$codename
 
-      ## libguestfs-tools, guestmount, guestunmount
-      ## - libguestfs-tools is not required in CI/VM.
-      ## - guestmount has been merged into libguestfs-tools in Debian.
-      ## - guestunmount is only available beginning from Jessie.
-      if [ "$BARE_METAL" = "1" ]; then
-         true "INFO: BARE_METAL is $BARE_METAL, installation of libguestfs-tools not required, ok."
-      else
-         ## install libguestfs-tools, guestmount, guestunmount
-         apt-get --yes \
-            $apt_timeout_opts \
-            $apt_unattended_opts \
-            -o APT::Default-Release="$default_release" \
-            install \
-            libguestfs-tools/$codename
-      fi
+      ## libguestfs-tools is not required in CI/VM.
 
       if [ "$CI" = "true" ]; then
          ## Small hack for CI.
@@ -385,10 +382,6 @@ Please delete Whonix's source code folder and get it again as user, not root!${r
          --list-cleanup \
          update
    fi
-
-   ## Sanity test.
-   command -v guestmount >/dev/null
-   command -v guestunmount >/dev/null
 
    ## }}}
 
