refactoring

diff --git a/build-steps.d/1100_sanity-tests b/build-steps.d/1100_sanity-tests
--- a/build-steps.d/1100_sanity-tests
+++ b/build-steps.d/1100_sanity-tests
@@ -85,10 +85,26 @@ check-virtualbox-vm-exists() {
    true
 }
 
+check_required_packages_installed() {
+   local required_packages_list required_package_item
+   local required_packages_list="git time curl apt-cacher-ng lsb-release fakeroot"
+
+   for required_package_item in $required_packages_list ; do
+      if ! dpkg-query --show --showformat='${Version}' "$required_package_item" ; then
+         error "${bold}${red}ERROR $BASH_SOURCE: Required package $required_package_item missing. Run:
+
+sudo apt-get update
+
+sudo apt-get install $required_packages_list${reset}"
+      fi
+   done
+}
+
 main() {
    root_check "$@"
    check-copy-vms-into-raw "$@"
    check-virtualbox-vm-exists "$@"
+   check_required_packages_installed "$@"
 }
 
 main "$@"
