sanity test

diff --git a/build-steps.d/1100_sanity-tests b/build-steps.d/1100_sanity-tests
--- a/build-steps.d/1100_sanity-tests
+++ b/build-steps.d/1100_sanity-tests
@@ -143,20 +143,23 @@ The user must fix this issue before proceeding. These issue is most likely not c
 }
 
 check-hostname() {
-   ## mmdebstrap requires /etc/hostname to exist.
+   ## mmdebstrap requires file '/etc/hostname' to exist.
    if ! test -f /etc/hostname ; then
       local local_hostname
       if ! local_hostname="$(hostname)" ; then
          error "${bold}${red}ERROR $BASH_SOURCE: Running command 'hostname' failed. See above.${reset}"
       fi
+      if [ "$local_hostname" = "" ]; then
+         error "${bold}${red}ERROR $BASH_SOURCE: Running command 'hostname' returned empty output. See above.${reset}"
+      fi
       true "${bold}${cyan}INFO: File /etc/hostname did not exist. Writing $local_hostname to /etc/hostname, ok.${reset}"
-      echo "$local_hostname" | $SUDO_TO_ROOT tee /etc/hostname >/dev/null
+      echo "$local_hostname" | $SUDO_TO_ROOT tee -- /etc/hostname >/dev/null
    fi
    if ! test -r /etc/hostname ; then
       error "${bold}${red}ERROR $BASH_SOURCE: /etc/hostname unreadable on the build system!${reset}"
    fi
    local build_system_hostname
-   if ! build_system_hostname=$(cat /etc/hostname) ; then
+   if ! build_system_hostname=$(cat -- /etc/hostname) ; then
       error "${bold}${red}ERROR $BASH_SOURCE: /etc/hostname reading failed the build system!${reset}"
    fi
    if [ "$build_system_hostname" = "" ]; then
