wip: Port to approx package caching proxy

diff --git a/build-steps.d/1200_prepare-build-machine b/build-steps.d/1200_prepare-build-machine
--- a/build-steps.d/1200_prepare-build-machine
+++ b/build-steps.d/1200_prepare-build-machine
@@ -238,61 +238,54 @@ check-git-folder() {
    fi
 }
 
-repo_proxy_setup() {
-   if [ "$REPO_PROXY" = "" ]; then
-      return 0
-   fi
-   if [ "$REPO_PROXY" = "none" ]; then
-      return 0
-   fi
-   if [ ! "$REPO_PROXY" = "http://127.0.0.1:3142" ]; then
+approx_proxy_setup() {
+   if [ ! "$APPROX_PROXY_ENABLE" = "yes" ]; then
       return 0
    fi
 
-   if apt-cacher-ng_config_check firstcheck ; then
-      true "INFO: apt-cacher-ng_config_check ok."
-      return 0
-   fi
+   ## approx requires an inetd implementation, thus this does not work.
+   #if [ "$DOCKER" = "true" ]; then
+   #   ## Find the process and kill it if running.
+   #   local pgrep_result approx_pids_list
+   #   pgrep_result="$(pgrep -f "approx")" || true
+   #   readarray -t approx_pids_list <<< "$pgrep_result"
+   #
+   #   for apt_cacher_ng_pid_item in "${apt_cacher_ng_pids_list[@]}"; do
+   #      $SUDO_TO_ROOT start-stop-daemon --stop --quiet --retry=TERM/5/KILL/5 --pid "$apt_cacher_ng_pid_item" || true
+   #   done
+   #
+   #   ## There is no systemd inside docker. Hence, manually restarting approx.
+   #   $SUDO_TO_ROOT /usr/sbin/approx &
+   #else
+   #   $SUDO_TO_ROOT systemctl restart approx-derivative-maker.socket
+   #fi
 
-   true "INFO: Adding 'AllowUserPorts: 0' to /etc/apt-cacher-ng/acng.conf"
-
-   ## Not possible because `append-once` requires `str_match`.
-   #$SUDO_TO_ROOT "$source_code_folder_dist/packages/kicksecure/helper-scripts/usr/bin/append-once" "/etc/apt-cacher-ng/acng.conf" "AllowUserPorts: 0"
-
-   ## Avoid apt-cacher-ng error:
-   ## > E: Failed to fetch http://HTTPS///deb.debian.org/debian-security/dists/bookworm-security/InRelease  403  Configuration error (confusing proxy mode) or prohibited port (see AllowUserPorts) [IP: 127.0.0.1 3142]
-   echo "AllowUserPorts: 0" | $SUDO_TO_ROOT tee -a "/etc/apt-cacher-ng/acng.conf" >/dev/null
-
-   ## Enable apt-cacher-ng HTTPS tunneling.
-   ## File /etc/apt-cacher-ng/zz_debconf.conf should already contain:
-   ## PassThroughPattern: .*
-   if ! grep --fixed-strings 'PassThroughPattern: .*' /etc/apt-cacher-ng/zz_debconf.conf ; then
-      echo 'PassThroughPattern: .*' | $SUDO_TO_ROOT tee -a "/etc/apt-cacher-ng/acng.conf" >/dev/null
-   fi
-
-   if [ "$DOCKER" = "true" ]; then
-      ## Find the process and kill it if running.
-      local pgrep_result apt_cacher_ng_pids_list
-      pgrep_result="$(pgrep -f "apt-cacher-ng")" || true
-      readarray -t apt_cacher_ng_pids_list <<< "$pgrep_result"
-
-      for apt_cacher_ng_pid_item in "${apt_cacher_ng_pids_list[@]}"; do
-         $SUDO_TO_ROOT start-stop-daemon --stop --quiet --retry=TERM/5/KILL/5 --pid "$apt_cacher_ng_pid_item" || true
-      done
-
-      ## There is no systemd inside docker. Hence, manually restarting apt-cacher-ng.
-      $SUDO_TO_ROOT /usr/sbin/apt-cacher-ng -c /etc/apt-cacher-ng &
+   # Install approx proxy configuration
+   $SUDO_TO_ROOT mkdir --parents -- '/etc/approx-derivative-maker'
+   $SUDO_TO_ROOT mkdir --parents -- '/var/cache/approx-derivative-maker'
+   $SUDO_TO_ROOT chown --recursive -- approx:approx '/var/cache/approx-derivative-maker'
+   $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/approx-derivative-maker.socket" '/usr/lib/systemd/system/approx-derivative-maker.socket'
+   if [ "$dist_build_sources_clearnet_or_onion" = "clearnet" ]; then
+      $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/approx-derivative-maker@.service" '/usr/lib/systemd/system/approx-derivative-maker@.service'
+      $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/approx.conf" '/etc/approx-derivative-maker/approx.conf'
+      safe-rm -rf -- '/etc/approx-derivative-maker/curl-home'
    else
-      $SUDO_TO_ROOT systemctl restart apt-cacher-ng.service
+      $SUDO_TO_ROOT mkdir --parents -- '/etc/approx-derivative-maker/curl-home'
+      $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/approx-derivative-maker-tor@.service" '/usr/lib/systemd/system/approx-derivative-maker@.service'
+      $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/approx-tor.conf" '/etc/approx-derivative-maker/approx.conf'
+      $SUDO_TO_ROOT cp -- "$source_code_folder_dist/approx/curlrc" '/etc/approx-derivative-maker/curl-home/.curlrc'
    fi
+
+   $SUDO_TO_ROOT systemctl daemon-reload
+   $SUDO_TO_ROOT systemctl restart approx-derivative-maker.socket
 
    if [ "$dist_build_redistributable" != "true" ]; then
       return 0
    fi
 
-   ## When building redistributeable builds, add `/var/cache/apt-cacher-ng` to Qubes bind-dirs on build machine.
+   ## When building redistributeable builds, add `/var/cache/approx to Qubes bind-dirs on build machine.
    $SUDO_TO_ROOT mkdir --parents /rw/config/qubes-bind-dirs.d
-   echo "binds+=( '/var/cache/apt-cacher-ng' )" | $SUDO_TO_ROOT tee -- /rw/config/qubes-bind-dirs.d/40_derivative-maker_acng.conf >/dev/null
+   echo "binds+=( '/var/cache/approx-derivative-maker' )" | $SUDO_TO_ROOT tee -- /rw/config/qubes-bind-dirs.d/40_derivative-maker_approx.conf >/dev/null
 
    true
 }
@@ -305,11 +298,11 @@ repo_proxy_test() {
       return 0
    fi
 
-   true "INFO: Testing REPO_PROXY $REPO_PROXY (most likely apt-cacher-ng, since default)..."
+   true "INFO: Testing REPO_PROXY $REPO_PROXY (most likely approx, since default)..."
    local curl_exit_code=0
    curl --fail --silent "$REPO_PROXY" || { curl_exit_code="$?" ; true; };
-   if [ "$curl_exit_code" = "22" ]; then
-      true "INFO: apt-cacher-ng functional..."
+   if [ "$curl_exit_code" = "0" ]; then
+      true "INFO: approx functional..."
       return 0
    fi
 
@@ -638,7 +631,7 @@ Defaults:%$USER runcwd=*
 }
 
 main() {
-   repo_proxy_setup "$@"
+   approx_proxy_setup "$@"
    repo_proxy_test "$@"
    build_machine_setup "$@"
    check-unicode "$@"
