build script: break when attempting to build from non-tagged git by default - https://phabricator.whonix.org/T231

diff --git a/build-steps.d/1200_create-debian-packages b/build-steps.d/1200_create-debian-packages
--- a/build-steps.d/1200_create-debian-packages
+++ b/build-steps.d/1200_create-debian-packages
@@ -131,6 +131,42 @@ signing_key() {
    true "INFO: END of $FUNCNAME"
 }
 
+check_for_untagged_commits() {
+   errorhandlersetup "errorhandlergeneral" ERR INT TERM
+
+   git_tag_nearest="$(git describe --always --abbrev=0)"
+   git_tag_current="$(git describe --always --abbrev=1000000000)"
+
+   ## Example git_tag_nearest:
+   ## 9.6
+
+   ## Example git_tag_current:
+   ## 10.0.0.3.7-developers-only-6-g505c39d44d2a08451f7ff53ce67d78745e05816b
+
+   true "${cyan}$BASH_SOURCE INFO: git_tag_nearest: $git_tag_nearest ${reset}"
+   true "${cyan}$BASH_SOURCE INFO: git_tag_current: $git_tag_current ${reset}"
+
+   if [ "$git_tag_nearest" == "$git_tag_current" ]; then
+      true "${cyan}$BASH_SOURCE INFO: Git reports tagged commit. ${reset}"
+   else
+      if [ "$whonix_build_ignore_untagged" = "true" ]; then
+         true "${bold}${cyan}$BASH_SOURCE INFO: Git reports a untagged commit! But you requested to ignore untagged commits, continuing... ${reset}"
+      else
+         true "${bold}${red}---------------------------------------------------------------------${reset}"
+         true "${bold}${red}$BASH_SOURCE ERROR: Git reports a untagged commit! ${reset}"
+         true "${cyan}$BASH_SOURCE INFO: (And you are not using ${under}--allow-untagged true${eunder}, \
+which you also should not do for security reasons, unless you are a developer or advanced user and know \
+what you are doing. Such as in case you added custom commits.) ${reset}"
+
+         true "${cyan}$BASH_SOURCE INFO: (See build documentation on how to verify and checkout git tags.)${reset}"
+         true "${bold}${red}---------------------------------------------------------------------${reset}"
+
+         error "Untagged commit! See above!"
+         true
+      fi
+   fi
+}
+
 check_for_uncommited_changes() {
    errorhandlersetup "errorhandlergeneral" ERR INT TERM
 
@@ -339,6 +375,7 @@ create-debian-packages() {
    errorhandlersetup "errorhandlergeneral" ERR INT TERM
 
    cleanup_old_packages
+   check_for_untagged_commits
    check_for_uncommited_changes
 
    true "${cyan}$BASH_SOURCE INFO: Going to update ${under}${WHONIX_BUILD_APT_CODENAME}${eunder} APT repository... ${reset}"
@@ -359,6 +396,18 @@ parse_cmd() {
            --flavor)
                if [ "$2" = "whonix-custom-workstation" ]; then
                   WHONIX_BUILD_CUSTOM_WORKSTATION="1"
+               fi
+               shift 2
+               ;;
+           --allow-untagged)
+               if [ "$2" = "false" ]; then
+                  true "${cyan}INFO: Would stop if building form untagged commits.${reset}"
+               elif [ "$2" = "true" ]; then
+                  true "${cyan}INFO: Would build form untagged commits.${reset}"
+                  export whonix_build_ignore_untagged="true"
+               else
+                  echo "${red}${bold}ERROR: supported options for --allow-untagged are 'true' or 'false'.${reset}"
+                  exit 1
                fi
                shift 2
                ;;
diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -209,6 +209,10 @@ whonix_build_one_script_help() {
 ## false: Break when uncommitted changes are found. Default.
 ## true: Do not use unless you know what you are doing.
 ##
+## --allow-untagged false|true
+## false: Break when build from non-tag. Default.
+## true: Do not use unless you know what you are doing.
+##
 ## --arch
 ## Only of interest for VM builds. Not for installations to root.
 ## i386: default, best tested.
@@ -545,6 +549,18 @@ whonix_build_one_parse_cmd() {
                ;;
            --retry-after)
                export whonix_build_dispatch_after_retry="$2"
+               shift 2
+               ;;
+           --allow-untagged)
+               if [ "$2" = "false" ]; then
+                  true "${cyan}INFO: Would stop if building form untagged commits.${reset}"
+               elif [ "$2" = "true" ]; then
+                  true "${cyan}INFO: Would build form untagged commits.${reset}"
+                  export whonix_build_ignore_untagged="true"
+               else
+                  echo "${red}${bold}ERROR: supported options for --allow-untagged are 'true' or 'false'.${reset}"
+                  exit 1
+               fi
                shift 2
                ;;
            --allow-uncommitted)
