get git submodules first before running unicode sanity test

diff --git a/build-steps.d/1200_prepare-build-machine b/build-steps.d/1200_prepare-build-machine
--- a/build-steps.d/1200_prepare-build-machine
+++ b/build-steps.d/1200_prepare-build-machine
@@ -234,6 +234,29 @@ build_machine_setup() {
    #$SUDO_TO_ROOT cat /proc/devices
 }
 
+check-unicode() {
+   local check_unicode_tool
+   check_unicode_tool="${dist_developer_meta_files_folder}/usr/bin/dm-check-unicode"
+   ## https://github.com/grml/grml-debootstrap/issues/219
+   ## overwrite with '|| true' because `grep` exits non-zero if no match was found.
+   ## TODO: dm-check-unicode currently hardcoded. Does not use source_code_folder_dist.
+
+   test -x "$check_unicode_tool"
+
+   grep_find_unicode_wrapper_output="$("$check_unicode_tool" "$source_code_folder_dist" 2>&1)" || true
+
+   if [ "$grep_find_unicode_wrapper_output" = "" ]; then
+      true "INFO: grep_find_unicode_wrapper_output empty, good, OK."
+   else
+      error "$0: ERROR: Unicode found!
+
+See also:
+https://forums.whonix.org/t/detecting-malicious-unicode-in-source-code-and-pull-requests/13754"
+   fi
+
+   true
+}
+
 repo_proxy_setup() {
    if [ "$REPO_PROXY" = "" ]; then
       return 0
@@ -374,6 +397,7 @@ main() {
    repo_proxy_setup "$@"
    repo_proxy_test "$@"
    build_machine_setup "$@"
+   check-unicode "$@"
    virtualbox_installer_repository "$@"
    grml-debootstrap_installation "$@"
    packages_installation_from_newer_repository "$@"
