fix

diff --git a/build-steps.d/1200_prepare-build-machine b/build-steps.d/1200_prepare-build-machine
--- a/build-steps.d/1200_prepare-build-machine
+++ b/build-steps.d/1200_prepare-build-machine
@@ -363,6 +363,12 @@ create-virtualbox-temporary-user() {
       return 0
    fi
 
+   ## Debugging. Because SUDO_TO_VBOX_TEMP is failing on CI.
+   if [ "$CI" = "true" ]; then
+      $SUDO_TO_ROOT cat /etc/sudoers || true
+      $SUDO_TO_ROOT ls -la /etc/sudoers.d || true
+   fi
+
    $SUDO_TO_ROOT adduser --quiet --system --group "dm-vbox-temp"
    $SUDO_TO_ROOT mkdir --parents "$HOMEVAR_VBOX_TEMP"
    $SUDO_TO_ROOT chown --recursive "dm-vbox-temp:dm-vbox-temp" "$HOMEVAR_VBOX_TEMP"
