generic variables names

diff --git a/build-steps.d/2600_create-vbox-vm b/build-steps.d/2600_create-vbox-vm
--- a/build-steps.d/2600_create-vbox-vm
+++ b/build-steps.d/2600_create-vbox-vm
@@ -22,7 +22,7 @@ general_setup() {
    ## Create a new VM. Name: $VMNAME
    sudo $SUDO_OPTS VBoxManage createvm --name "$VMNAME" --register
 
-   if ! echo "$BUILD_TARGET_ARCH" | grep "64" ; then
+   if ! echo "$dist_build_target_arch" | grep "64" ; then
       sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ostype Debian
    else
       sudo $SUDO_OPTS VBoxManage modifyvm "$VMNAME" --ostype Debian_64
@@ -367,26 +367,26 @@ main() {
    ## https://forums.whonix.org/t/whonix-vulerable-due-to-missing-processor-microcode-packages/5739/22
    #spectre_meltdown_defenses
 
-   if [ "$WHONIX_BUILD_TYPE" = "gateway" ]; then
+   if [ "$dist_build_type_long" = "gateway" ]; then
       whonix-gateway_specific
       dns_specific
       ## For screen reader support.
       audio_enable
-   elif [ "$WHONIX_BUILD_TYPE" = "workstation" ]; then
+   elif [ "$dist_build_type_long" = "workstation" ]; then
       whonix-workstation_specific
       audio_enable
-   elif [ "$WHONIX_BUILD_TYPE" = "custom-workstation" ]; then
+   elif [ "$dist_build_type_long" = "custom-workstation" ]; then
       whonix-custom-workstation_specific
       audio_enable
-   elif [ "$WHONIX_BUILD_TYPE" = "whonix-host" ]; then
+   elif [ "$dist_build_type_long" = "whonix-host" ]; then
       debian_specific
       dns_specific
       audio_enable
-   elif [ "$WHONIX_BUILD_SHORT_TYPE" = "kicksecure" ]; then
+   elif [ "$dist_build_type_short" = "kicksecure" ]; then
       debian_specific
       audio_enable
    else
-      error "ERROR: Invalid WHONIX_BUILD_FLAVOR $WHONIX_BUILD_FLAVOR. Please report this bug!"
+      error "ERROR: Invalid dist_build_flavor $dist_build_flavor. Please report this bug!"
    fi
 
    debugging
