sanity test: check if virtual hard drive exists before proceeding with VM creation

diff --git a/build-steps.d/2600_create-vbox-vm b/build-steps.d/2600_create-vbox-vm
--- a/build-steps.d/2600_create-vbox-vm
+++ b/build-steps.d/2600_create-vbox-vm
@@ -334,6 +334,10 @@ main() {
       return 0
    fi
 
+   if ! test -e "$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi" ; then
+      error "ERROR: virtual hard drive file '$HOMEVAR/VirtualBox VMs/$VMNAME/$VMNAME.vdi' does not exist!"
+   fi
+
    root_check
    general_setup
 
