echos

diff --git a/whonix_shared/usr/local/bin/uwt b/whonix_shared/usr/local/bin/uwt
--- a/whonix_shared/usr/local/bin/uwt
+++ b/whonix_shared/usr/local/bin/uwt
@@ -89,7 +89,7 @@ usage () {
 }
 
 set_id () {
-	echo "ERROR: $1 is set${2}id. usewithtor will not work on a set${2}id executable." >&2
+	echo "UWT ERROR: $1 is set${2}id. usewithtor will not work on a set${2}id executable." >&2
 	exit 1
 }
 
@@ -132,22 +132,22 @@ while [ -n "$1" ]; do
 done
 
 if [ -z "$ip" ]; then
-	echo "ERROR: ip (-i) missing." >&2
+	echo "UWT ERROR: ip (-i) missing." >&2
 	exit 1
 fi
 
 if [ -z "$port" ]; then
-	echo "ERROR: port (-p) missing." >&2
+	echo "UWT ERROR: port (-p) missing." >&2
 	exit 1
 fi
 
 if [ -z "$server_type" ]; then
-	echo "ERROR: server type (-t) missing." >&2
+	echo "UWT ERROR: server type (-t) missing." >&2
 	exit 1
 fi
 
 if [ -z "$command" ]; then
-	echo "ERROR: command is missing." >&2
+	echo "UWT ERROR: command is missing." >&2
 	exit 1
 fi
 
@@ -171,7 +171,7 @@ if [ ! -x "$TORSOCKS" ]; then
 fi
 
 if [ "$UWT_VERBOSE" = "1" ]; then
-	echo "We are armed with the following torsocks: $TORSOCKS"
+	echo "UWT: We are armed with the following torsocks: $TORSOCKS"
 fi
 
 ## Define our torsocks config file.
