whonix_shared/usr/local/bin/uwtwrapper: added sanity tests

diff --git a/whonix_shared/usr/local/bin/uwtwrapper b/whonix_shared/usr/local/bin/uwtwrapper
--- a/whonix_shared/usr/local/bin/uwtwrapper
+++ b/whonix_shared/usr/local/bin/uwtwrapper
@@ -6,7 +6,7 @@
 ## globally or for certain applications, see /etc/whonix.d/.
 
 ## Debugging.
-set -x
+#set -x
 
 trap "error_handler" ERR
 
@@ -21,6 +21,24 @@ echo "
 "
 exit 1
 }
+
+## sanity tests
+if [ ! -e /usr/local/bin/uwt ]; then
+   echo "$SCRIPTNAME uwt wrapper ERROR: /usr/local/bin/uwt does not exist."
+   exit 1
+fi
+if [ ! -x /usr/local/bin/uwt ]; then
+   echo "$SCRIPTNAME uwt wrapper ERROR: /usr/local/bin/uwt is not executable."
+   exit 1
+fi
+if [ ! -e /usr/bin/"$SCRIPTNAME" ]; then
+   echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/"$SCRIPTNAME" does not exist."
+   exit 1
+fi
+if [ ! -x /usr/bin/"$SCRIPTNAME" ]; then
+   echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/"$SCRIPTNAME" is not executable."
+   exit 1
+fi
 
 ## Files in /etc/whonix.d/* set variables such as
 ## port_aptget, port_gpg, ... and variables such as
