fixes

diff --git a/aos_gateway/usr/local/bin/leaktest b/aos_gateway/usr/local/bin/leaktest
--- a/aos_gateway/usr/local/bin/leaktest
+++ b/aos_gateway/usr/local/bin/leaktest
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-  if [ "$(id -u)" != "0" ]; then
-     echo "FATAL ERROR: This script must be run as root (sudo)"
-     exit 1
-  fi
+if [ "$(id -u)" != "0" ]; then
+   echo "FATAL ERROR: This script must be run as root (sudo)"
+   exit 1
+fi
 
 exit_function() {
 echo "INFO: Listing for leaks stopped."
@@ -26,7 +26,10 @@ exit 1
 trap "exit_function" ERR INT TERM
 
 # Install wireshark to the aos-Gateway for Leak Testing
-echo "INFO: Installing tshark if it is not installed yet"
+echo "INFO: Running apt-get update..."
+apt-get update
+
+echo "INFO: Installing tshark if it is not installed yet."
 apt-get --yes install tshark
 
 echo "INFO: You can uninstall tshark later manually using:"
