improved error handling

diff --git a/derivative-update b/derivative-update
--- a/derivative-update
+++ b/derivative-update
@@ -348,7 +348,7 @@ update_repo() {
   if [ "${target_tag}" = 'latest' ]; then
     latest_tag_commit="$(git rev-list --tags --max-count=1)" || error 'Failed to find latest tag commit.'
     [[ -z "$latest_tag_commit" ]] && error 'No tags found.'
-    target_tag="$(git describe --tags -- "$latest_tag_commit")"
+    target_tag="$(git describe --tags -- "$latest_tag_commit")" || error 'Failed to find latest git tag.'
   fi
 
   ## Verify the specified ref, then check out that ref.
