quotes

diff --git a/derivative-update b/derivative-update
--- a/derivative-update
+++ b/derivative-update
@@ -277,8 +277,8 @@ update_repo() {
   ## use" (TOFU) security.
   verify_ref "${orig_ref}" 'commit'
 
-  if ! test -f .gitmodules ; then
-    error "Missing .gitmodules file."
+  if ! test -f '.gitmodules' ; then
+    error "Missing '.gitmodules' file."
   fi
 
   ## "Get rid of" uncommitted changes, we need there to be no uncommitted
