code simplification

diff --git a/derivative-update b/derivative-update
--- a/derivative-update
+++ b/derivative-update
@@ -357,42 +357,42 @@ update_repo() {
     git checkout --recurse-submodules "${target_ref}" || error "'git checkout --recurse-submodules' failed."
 
     git show-ref --verify -- "refs/heads/${target_ref}" || error "'git show-ref --verify' failed."
+  fi
 
-    ## The specified ref is a branch, and the user asked us to update from
-    ## the remote repository, meaning the user is trying to update to the
-    ## latest commit of the specified branch.
-    ##
-    ## Merge the branch with its remote (which we fetched earlier), then
-    ## re-verify the branch. If it flunks verification, try to fix
-    ## the local branch, then revert to the original ref.
-    ##
-    ## Note that we make a best-effort attempt to get the local branch
-    ## back to a known-good state in the event the branch flunks
-    ## verification. If that attempt fails, we ignore the failure since
-    ## it's important to get the working tree back into a known-good state
-    ## if at all possible. Thus it is possible that failed verification
-    ## during a branch update could lead to a compromised local branch.
+  ## The specified ref is a branch, and the user asked us to update from
+  ## the remote repository, meaning the user is trying to update to the
+  ## latest commit of the specified branch.
+  ##
+  ## Merge the branch with its remote (which we fetched earlier), then
+  ## re-verify the branch. If it flunks verification, try to fix
+  ## the local branch, then revert to the original ref.
+  ##
+  ## Note that we make a best-effort attempt to get the local branch
+  ## back to a known-good state in the event the branch flunks
+  ## verification. If that attempt fails, we ignore the failure since
+  ## it's important to get the working tree back into a known-good state
+  ## if at all possible. Thus it is possible that failed verification
+  ## during a branch update could lead to a compromised local branch.
 
-    ## Save the ref first so we can undo the merge if it goes wrong.
-    ## NOTE: Cannot use end-of-options ("--").
-    branch_reset_ref="$(git rev-parse HEAD)" || error 'Cannot get head commit ID!'
+  ## Save the ref first so we can undo the merge if it goes wrong.
+  ## NOTE: Cannot use end-of-options ("--").
+  branch_reset_ref="$(git rev-parse HEAD)" || error 'Cannot get head commit ID!'
 
-    ## Safe.
-    ## Ensures submodules' remote URL configuration matches the values specified in .gitmodules.
-    git submodule sync --recursive || error "'git submodule sync --recursive' failed."
+  ## Do merge and verify.
+  ## If any of the steps involved fail, trigger a rollback.
+  current_branch="$(git symbolic-ref -q -- HEAD)" \
+    || abort_update \
+      'Getting current branch name failed!' \
+      "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
 
-    ## Do merge and verify.
-    ## If any of the steps involved fail, trigger a rollback.
-    current_branch="$(git symbolic-ref -q -- HEAD)" \
-      || abort_update \
-        'Getting current branch name failed!' \
-        "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
+  upstream_branch="$(git for-each-ref --format='%(upstream:short)' "$current_branch")" \
+    || abort_update \
+      'Getting upstream branch name failed!' \
+      "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
 
-    upstream_branch="$(git for-each-ref --format='%(upstream:short)' "$current_branch")" \
-      || abort_update \
-        'Getting upstream branch name failed!' \
-        "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
-
+  if [ -n "${target_tag}" ]; then
+    true "Special code path unnecessary for git tag."
+  elif [ -n "${target_ref}" ]; then
     git merge --ff-only "$upstream_branch" \
       || abort_update \
         'Merge from remote failed!' \
@@ -402,15 +402,26 @@ update_repo() {
       || abort_update \
         'Remote commit verification failed! You are now in detached HEAD state, you will need to check out a branch you trust manually.' \
         "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
+  fi
 
-    ## Caution.
-    ## This command updates Git submodules to the commit recorded in the parent repository. (derivative-maker)
-    ## It modifies the submodule's Git HEAD, potentially overriding local changes.
-    git -c merge.verifySignatures=true submodule update --init --recursive --jobs=200 --merge \
+  ## Safe.
+  ## Ensures submodules' remote URL configuration matches the values specified in .gitmodules.
+  git submodule sync --recursive || error "'git submodule sync --recursive' failed."
+
+  ## Caution.
+  ## This command updates Git submodules to the commit recorded in the parent repository. (derivative-maker)
+  ## It modifies the submodule's Git HEAD, potentially overriding local changes.
+  git -c merge.verifySignatures=true submodule update --init --recursive --jobs=200 --merge \
+    || abort_update \
+      'Submodule update failed!' \
+      "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
+
+  if [ -n "${target_tag}" ]; then
+    verify_ref "${target_ref}" 'tag' \
       || abort_update \
-        'Submodule update failed!' \
+        'Verification failed after submodule update!' \
         "${did_stash_changes}" "${orig_ref}" "${branch_reset_ref}"
-
+  elif [ -n "${target_ref}" ]; then
     verify_ref "${target_ref}" 'commit' \
       || abort_update \
         'Verification failed after submodule update!' \
