guard against missing .gitmodules file

diff --git a/derivative-update b/derivative-update
--- a/derivative-update
+++ b/derivative-update
@@ -265,6 +265,10 @@ update_repo() {
   ## use" (TOFU) security.
   verify_ref "${orig_ref}^{commit}" 'commit'
 
+  if ! test -f .gitmodules ; then
+        error "Missing .gitmodules file."
+  fi
+
   ## "Get rid of" uncommitted changes, we need there to be no uncommitted
   ## changes in order to robustly verify the repository state. How we do this
   ## depends on the options we were passed:
