Fix.

diff --git a/whonix_build b/whonix_build
--- a/whonix_build
+++ b/whonix_build
@@ -66,6 +66,10 @@ whonix_build_machine() {
       root_check
 
       trap "build_error_handler" ERR
+      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-delete
+      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+
+      trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createimg
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
