fixes

diff --git a/whonix_build b/whonix_build
--- a/whonix_build
+++ b/whonix_build
@@ -74,10 +74,6 @@ whonix_build_machine() {
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
-      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-convertfromraw
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
-
-      trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyinto-pre
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
@@ -87,6 +83,10 @@ whonix_build_machine() {
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyinto-post
+      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+
+      trap "build_error_handler" ERR
+      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-convertfromraw
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
