$USERNAME -> "$USERNAME"

diff --git a/whonix_build b/whonix_build
--- a/whonix_build
+++ b/whonix_build
@@ -30,14 +30,14 @@ set -x
 
 
 build_error_handler() {
-   touch /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED
+   touch /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED
    exit 1
 }
 
 
 
 USERNAME="user"
-WHONIX_SOURCE_FOLDER="/home/$USERNAME/Whonix"
+WHONIX_SOURCE_FOLDER="/home/"$USERNAME"/Whonix"
 FAST=0
 
 
@@ -58,7 +58,7 @@ fi
 
 
 # If this file was created previously, delete it now.
-rm /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED || true
+rm /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED || true
 
 
 
@@ -67,42 +67,42 @@ whonix_build_machine() {
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-vboxdelete
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       if [ "$FAST" = "0" ]; then
          trap "build_error_handler" ERR
          "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createimg
-         if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+         if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
       fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyimg
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyinto
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-chroot
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       ## Commented out. Needs to much time, space and is only required for redistribution.
       #"$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-source
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-converttovdi
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createvboxvm
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-export
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ -f /home/"$USERNAME"/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
       echo "INFO: No errors."
