Running damngpl to create a list of gpl software and downloading all gpl sources to the /home/user/whonix_binary/sources/ folder.

diff --git a/whonix_build b/whonix_build
--- a/whonix_build
+++ b/whonix_build
@@ -86,6 +86,10 @@ whonix_build_machine() {
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
       trap "build_error_handler" ERR
+      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-source
+      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+
+      trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-converttovdi
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
