whonix_build: added -fast switch, which skips the -createimg step.

diff --git a/whonix_build b/whonix_build
--- a/whonix_build
+++ b/whonix_build
@@ -9,6 +9,9 @@ script_help() {
 # -all
 # build both Virtual machines
 #
+# -fast
+# skips the -createimg step
+#
 # -tg
 # Builds Whonix-Gateway VBox machine.
 #
@@ -35,6 +38,7 @@ build_error_handler() {
 
 USERNAME="user"
 WHONIX_SOURCE_FOLDER="/home/$USERNAME/Whonix"
+FAST=0
 
 
 
@@ -65,9 +69,11 @@ whonix_build_machine() {
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-vboxdelete
       if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
 
-      trap "build_error_handler" ERR
-      "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createimg
-      if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      if [ "$FAST" = "0" ]; then
+         trap "build_error_handler" ERR
+         "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-createimg
+         if [ -f /home/$USERNAME/whonix_binary/WHONIX_BUILD_FAILED ]; then echo "BUILD SCRIPT ERROR: Failed!"; exit 0; fi
+      fi
 
       trap "build_error_handler" ERR
       "$WHONIX_SOURCE_FOLDER"/whonix_createvm -t"$MACHINE"-copyimg
@@ -156,6 +162,18 @@ fi
 # -all                                                         #
 ################################################################ 
 if [[ "$1" = "-all" ]]; then
+	MACHINE="g"
+	whonix_build_machine
+	MACHINE="w"
+	whonix_build_machine
+	exit 0
+fi
+
+################################################################ 
+# -fast                                                        #
+################################################################ 
+if [[ "$1" = "-fast" ]]; then
+        FAST=1
 	MACHINE="g"
 	whonix_build_machine
 	MACHINE="w"
