whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks: improvements, CI

diff --git a/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks b/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
--- a/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
+++ b/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
@@ -35,17 +35,46 @@ sync
 true "INFO: Checking if sysctcl -p runs without an error."
 sysctl -p
 
-true "INFO: Listing packages (or debs) which do not have an MD5 sums file..."
+true "INFO: Checking if debsums is installed."
+command -v debsums >/dev/null
 
-debsums --list-missing
+true "INFO: Trying to find out if there are packages (or debs) which do not have an MD5 sums file..."
 
-true "INFO: Listed missing debs."
+return_code="0"
+debsums_return1="$(debsums --list-missing 2>&1)" || { return_code="$?" ; true; };
 
-true "INFO: Listing missing files..."
+if [ ! "$return_code" = "0" ]; then
+   error "ERROR: debsums returned a non-zero return_code: $return_code!"
+fi
 
-debsums --silent
+if [ "$debsums_return1" = "" ]; then
+   true "INFO: Ok, no packages (or debs) with missing MD5 sums file found."
+else
+   if [ "$CI" = "true" ]; then
+      true "INFO: Packages (or debs) with missing MD5 sums file found! Continuing, because CI detected."
+   else
+      error "ERROR: Packages (or debs) with missing MD5 sums file found!"
+   fi
+fi
 
-true "INFO: Listed missing files."
+true "INFO: Trying to find out if there are any packages (or debs) with missing files..."
+
+return_code="0"
+debsums_return2="$(debsums --silent 2>&1)" || { return_code="$?" ; true; };
+
+if [ ! "$return_code" = "0" ]; then
+   error "ERROR: debsums returned a non-zero return_code: $return_code!"
+fi
+
+if [ "$debsums_return2" = "" ]; then
+   true "INFO: Ok, no packages (or debs) with missing files file found."
+else
+   if [ "$CI" = "true" ]; then
+      true "INFO: Packages (or debs) with missing files found! Continuing, because CI detected."
+   else
+      error "ERROR: Packages (or debs) with missing files found!"
+   fi
+fi
 
 true "INFO: Listing changed configuration files..."
 true "      (Only an information, no check...)"
@@ -53,6 +82,7 @@ true "      (Has to be reviewed manually by the builder.)"
 true "      (A differencing /etc/resolv.conf.whonix is expected when building \
 Virtual Machine images, because the /etc/resolv.conf from the host has been mounted inside the image.)"
 
-debsums --config --silent || true
+return_code="0"
+debsums_return3="$(debsums --config --silent 2>&1)" || { return_code="$?" ; true; };
 
 true "INFO: Listed changed configuration files."
