whonix_shared/usr/lib/whonix/whonixcheck/37_check_tor_bootstrap: added SocksPort open test; output; refactoring; comments

diff --git a/whonix_shared/usr/lib/whonix/whonixcheck/37_check_tor_bootstrap b/whonix_shared/usr/lib/whonix/whonixcheck/37_check_tor_bootstrap
--- a/whonix_shared/usr/lib/whonix/whonixcheck/37_check_tor_bootstrap
+++ b/whonix_shared/usr/lib/whonix/whonixcheck/37_check_tor_bootstrap
@@ -7,7 +7,44 @@
 check_tor_bootstrap() {
    trap "error_handler" ERR
 
-   ## Small check if Control Port Filter Proxy is functional.
+   ## {{ Small check if one of Tor's SocksPorts is functional.
+
+   local SOCKS_PORT_WHONIXCHECK="9110"
+
+   $CURL \
+      --fail \
+      $CURL_VERBOSE \
+      --max-time 5 \
+      --output "$VERIFY_TEMPDIR/socks_port_open_file" \
+      "$GATEWAY_IP:$SOCKS_PORT_WHONIXCHECK" \
+      &
+
+   ## Example OK:
+   ## curl: (22) The requested URL returned error: 501 Tor is not an HTTP Proxy
+
+   ## Example Failure:
+   ## curl: (56) Recv failure: Connection reset by peer
+
+   wait "$!" || { check_socks_port_open_test="$?" ; true; };
+
+   #local curl_status_message="$(/usr/lib/whonix/curl_return_codes "$check_socks_port_open_test")"
+
+   ## TODO
+   if [ "$check_socks_port_open_test" = "22" ]; then
+      ## OK.
+      true
+   elif [ "$check_socks_port_open_test" = "57" ]; then
+      ## Failure.
+      true
+   else
+      ## Unexpected error.
+      true
+   fi
+
+   ## }}
+
+   ## {{ Small check if Control Port Filter Proxy is functional.
+
    ## Only testing on Whonix-Gateway, because Control Port Filter Proxy only
    ## runs on Whonix-Gateway.
    local i="0"
@@ -32,12 +69,20 @@ File /var/run/controlportfilt/ownrunning does not exist. Please report this Whon
       fi
    fi
 
+   ## }}
+
+   ## {{ variables
+
    local kill_after="5s"
    local timeout_after="5s"
    local script="/usr/lib/whonix/whonixcheck/help_check_tor_bootstrap.py"
 
-   ## Sometimes it does not work on the first run. Small hack.
+   ## }}
+
+   ## {{ Sometimes it does not work on the first run. Small hack.
+
    local bootstrap_file="$VERIFY_TEMPDIR/tor_bootstrap_temp"
+   rm --force "$bootstrap_file"
    local temp_return="0"
    timeout --kill-after="$kill_after" "$timeout_after" "$script" 2>&1 >"$bootstrap_file" &
    wait "$!" || { local temp_return="$?" ; true; }
@@ -51,6 +96,10 @@ File /var/run/controlportfilt/ownrunning does not exist. Please report this Whon
       local temp_status="ERROR: File "$bootstrap_file" does not exist. Please report this Whonix bug!"
    fi
 
+   ## }}
+
+   ## {{ actual check
+
    if [ "$TOR_BOOTSTRAP_TIME_START" = "" ]; then
       TOR_BOOTSTRAP_TIME_START="$(date +%s)"
    fi
@@ -58,6 +107,7 @@ File /var/run/controlportfilt/ownrunning does not exist. Please report this Whon
    TOR_BOOTSTRAP_TIME_PASSED="$(expr "$TOR_BOOTSTRAP_TIME_NOW" - "$TOR_BOOTSTRAP_TIME_START")" || true
 
    local bootstrap_file="$VERIFY_TEMPDIR/tor_bootstrap_file"
+   rm --force "$bootstrap_file"
    tor_bootstrap_percent="0"
    timeout --kill-after="$kill_after" "$timeout_after" "$script" 2>&1 >"$bootstrap_file" &
    wait "$!" || { tor_bootstrap_percent="$?" ; true; }
@@ -65,11 +115,13 @@ File /var/run/controlportfilt/ownrunning does not exist. Please report this Whon
    if [ -f "$bootstrap_file" ]; then
       tor_bootstrap_status="$(cat "$bootstrap_file")"
       if [ "$tor_bootstrap_status" = "" ]; then
-         tor_bootstrap_status="ERROR: Variable tor_bootstrap_status is empty. Please report this Whonix bug!"
+         tor_bootstrap_status="Variable tor_bootstrap_status is empty."
       fi
    else
       tor_bootstrap_status="ERROR: File $bootstrap_file does not exist. Please report this Whonix bug!"
    fi
+
+   ## }}
 
    ## `timeout` returns:
    ## - 124 if sigterm was sufficient
@@ -85,11 +137,13 @@ File /var/run/controlportfilt/ownrunning does not exist. Please report this Whon
          local MSG="Tor Bootstrap Result:
 Tor's Control Port could not be reached. (Code: "$tor_bootstrap_percent")
 (tor_bootstrap_status: $tor_bootstrap_status)
+(check_socks_port_open_test: $check_socks_port_open_test)
 Please report this Whonix bug!"
       elif [ "$VM" = "Whonix-Workstation" ]; then
          local MSG="Tor Bootstrap Result:
 Tor's Control Port could not be reached. (Code: "$tor_bootstrap_percent")
 (tor_bootstrap_status: $tor_bootstrap_status)
+(check_socks_port_open_test: $check_socks_port_open_test)
 Did you start Whonix-Gateway beforehand?
 Please run whonixcheck on Whonix-Gateway."
       else
@@ -105,6 +159,7 @@ Please run whonixcheck on Whonix-Gateway."
       local MSG="Tor Bootstrap Result:
 "$script" ERROR ($tor_bootstrap_percent).
 (tor_bootstrap_status: $tor_bootstrap_status)
+(check_socks_port_open_test: $check_socks_port_open_test)
 Please report this Whonix bug!"
       $output ${output_opts[@]} --channel "both" --type "error" --title "$TITLE" --message "$MSG"
       EXIT_CODE="1"
