code formatting, comments

diff --git a/whonix_workstation/usr/local/share/whonix/whonix_internal_install_script b/whonix_workstation/usr/local/share/whonix/whonix_internal_install_script
--- a/whonix_workstation/usr/local/share/whonix/whonix_internal_install_script
+++ b/whonix_workstation/usr/local/share/whonix/whonix_internal_install_script
@@ -224,38 +224,39 @@ dummytor() {
 # -install
 ######################################################
 if [[ "$1" = "-install" ]]; then
-root_check                # Depends on nothing.
+   root_check                ## Depends on nothing.
 
-workstation_source        # Depends on nothing.
-whonix_internal_checks    # Depends on nothing.
-whonix_create_swap_file   # Depends on root_check, not being run again when in use.
-whonix_config_uuids_fstab # Depends on root_check, not being run again after adding new hdds.
-adduser_user              # Depends on root_check.
-add_crontab_for_user      # Depends on nothing.
+   workstation_source        ## Depends on nothing.
+   whonix_internal_checks    ## Depends on nothing.
+   whonix_create_swap_file   ## Depends on root_check, not being run again when in use.
+   whonix_config_uuids_fstab ## Depends on root_check, not being run again after adding new hdds.
+   adduser_user              ## Depends on root_check.
+   add_crontab_for_user      ## Depends on nothing.
 
-# Building in the clear and behind a transparent Tor proxy is supported.
-# In case we are not behind a Whonix-Gateway with dedicated ports for
-# Tor Browser download, use TransPort or clear download instead of SocksPort.
-sudo -u user /usr/local/bin/torbrowser -dev-build-passthrough # Depends on working internet connection.
+   ## Building in the clear and behind a transparent Tor proxy is supported.
+   ## In case we are not behind a Whonix-Gateway with dedicated ports for
+   ## Tor Browser download, use TransPort or clear download instead of SocksPort.
+   sudo -u user /usr/local/bin/torbrowser -dev-build-passthrough ## Depends on working internet connection.
 
-config_irc_xchat          # Depends on root_check.
-config_symlinks           # Depends on root_check.
-config_audio              # Depends on root_check.
-config_gpg                # Depends on nothing.
-config_htp                # Depends on root_check.
-config_wpolipo            # Depends on root_check.
-config_misc	          # Depends on root_check.
-whonix_kde                # Depends on nothing.
-dummytor                  # Depends on root_check.
+   config_irc_xchat          ## Depends on root_check.
+   config_symlinks           ## Depends on root_check.
+   config_audio              ## Depends on root_check.
+   config_gpg                ## Depends on nothing.
+   config_htp                ## Depends on root_check.
+   config_wpolipo            ## Depends on root_check.
+   config_misc	             ## Depends on root_check.
+   whonix_kde                ## Depends on nothing.
+   dummytor                  ## Depends on root_check.
 
-whonix_chroot_misc        # Depends on root_check. (/usr/local/share/whonix/whonix_chroot_shared)
-whonix_bannned_packages   # Depends on root_check. (/usr/local/share/whonix/whonix_chroot_shared)
-whonix_slim_down          # Depends on root_check, being last function. (/usr/local/share/whonix/whonix_chroot_shared)
+   whonix_chroot_misc        ## Depends on root_check. (/usr/local/share/whonix/whonix_chroot_shared)
+   whonix_bannned_packages   ## Depends on root_check. (/usr/local/share/whonix/whonix_chroot_shared)
+   whonix_slim_down          ## Depends on root_check, being last function. (/usr/local/share/whonix/whonix_chroot_shared)
 
-sync                      # Ensure changes get written to disk.
+   sync                      ## Ensure changes get written to disk.
 
-echo "Script completed, this indicates neither success nor failure." >&2
-exit 0
+   echo "Script completed, this indicates neither success nor failure." >&2
+   exit 0
+
 fi
 
 
