whonix_shared/usr/share/whonix/chroot-scripts-post.d/70_log_build_version: added sanity test; comment

diff --git a/whonix_shared/usr/share/whonix/chroot-scripts-post.d/70_log_build_version b/whonix_shared/usr/share/whonix/chroot-scripts-post.d/70_log_build_version
--- a/whonix_shared/usr/share/whonix/chroot-scripts-post.d/70_log_build_version
+++ b/whonix_shared/usr/share/whonix/chroot-scripts-post.d/70_log_build_version
@@ -25,7 +25,14 @@ case $WHONIX_BUILD_SKIP_SCRIPTS in
                     ;;
 esac
 
+## Info.
 echo "INFO: Logging whonix_build_whonix_version_new $whonix_build_whonix_version_new to /usr/share/whonix/build_version..."
+
+## Sanity test.
+if [ "$whonix_build_whonix_version_new" = "" ]; then
+   echo "ERROR: whonix_build_whonix_version_new is empty! Please report this bug!"
+   exit 1
+fi
 
 ## Support re-running the script.
 rm --force "/usr/share/whonix/build_version"
