fixes

diff --git a/aos_shared/usr/local/bin/torcheck b/aos_shared/usr/local/bin/torcheck
--- a/aos_shared/usr/local/bin/torcheck
+++ b/aos_shared/usr/local/bin/torcheck
@@ -14,6 +14,7 @@
 #
 # zenity --display=:0.0 is required to make it compatible with cron
 # see http://promberger.info/linux/2009/01/02/running-x-apps-like-zenity-from-crontab-solving-cannot-open-display-problem/
+# --no-markup to allow showing "&" see https://bugzilla.gnome.org/show_bug.cgi?id=621907
 #
 # We would prefer a popup free solution. As soon as the timeout bug in
 # notify-send is fixed, we swtich to notify-send.
@@ -36,15 +37,18 @@
 
 error_handler() {
    show_output
-   echo "
-##################################################
-# torcheck script bug                            #
-# Run: torcheck -v                               #
-# for verbose output. Clean the output and       #
-# please report this bug!                        #
-# bash_commend: $BASH_COMMAND                    #
-##################################################
-        "
+   
+   ZENITY_MESSAGE=""
+   
+   local MSG="torcheck script bug
+Run: torcheck -v
+for verbose output. Clean the output and
+please report this bug!
+bash_commend: $BASH_COMMAND"
+   echo "$MSG"
+   output "--error" "ERROR" "$MSG"
+   show_output
+   
    exit 1
 }
 
@@ -242,7 +246,8 @@ $BITCOIN_ADDRESS"
       output "--info" "Info" "$MSG"  
    fi
    
-   zenity --display=:0.0 --height=600 --width=800 --timeout 86400 --title="$VM $INSTALLED_AOS_VERSION $ZENITY_TITLE `date`" "$ZENITY_TYPE" --text "$ZENITY_MESSAGE" &
+   zenity --display=:0.0 --height=600 --width=800 --timeout 86400 --no-markup \
+   --title="$VM $INSTALLED_AOS_VERSION $ZENITY_TITLE `date`" "$ZENITY_TYPE" --text "$ZENITY_MESSAGE" &
 }
 
 
@@ -259,10 +264,11 @@ Running checks..."
    # TODO: After the timeout bug has been fixed upstream, --expire-time has to be set to 30.
    #notify-send --urgency low --expire-time 0 --app-name "aos" "$NOTIFY_MSG"
    local NOTIFY_MSG="Checking time synchronization, Tor connection, Tor Browser version, operating system updates, aos version, aos news...
-This will happen in background. You will be notified about the result in approximately 15 to 30 seconds."
+This will happen in background and will take approximately 60 seconds."
 
    # The progress window will close automatically after 100% progress.
-   exec 3> >(zenity --display=:0.0 --timeout 86400 --title="$VM $INSTALLED_AOS_VERSION Info `date`" "--progress" --auto-close --auto-kill --text "$NOTIFY_MSG")
+   exec 3> >(zenity --display=:0.0 --timeout 86400 --no-markup \
+   --title="$VM $INSTALLED_AOS_VERSION Info `date`" "--progress" --auto-close --auto-kill --text "$NOTIFY_MSG")
 }
 
 
@@ -275,7 +281,7 @@ aos is experimental software by means of concept and design. Do not rely on it f
 $AOS_HOMEPAGE"
 
    echo "$MSG"
-   output "--info" "Info" "$MSG"
+   output "--info" "Info" "$MSG"   
 }
 
 
@@ -482,24 +488,46 @@ $IP"
 
 
 
-check_operating_system() {
-   trap "error_handler" ERR INT TERM
+error_handler_check_operating_system() {
+      local MSG="Could not check for operating system updates.
+Please check by manually running:
+sudo apt-get update
+sudo apt-get dist-upgrade"
+      echo "$MSG"
+      output "--error" "WARNING" "$MSG"
+}
 
+
+
+check_operating_system() {
+   trap "error_handler_check_operating_system" ERR INT TERM
+   
    # Runing apt-get update as user (non-root).
    # Depends on exception set in /etc/sudoers.   
    # Minmal custom script.
    echo "Checking for operating system updates..."
    sudo /usr/local/bin/apt-get-update >/dev/null
+   
+   trap "error_handler" ERR INT TERM
 
    # /etc/update-motd.d/90-updates-available
    # /usr/lib/update-notifier/update-motd-updates-available
    # /usr/lib/update-notifier/apt-check
    NEED_UPDATE_CHECK=yes
    local RESULT="`/usr/lib/update-notifier/apt-check --human-readable`"
-   local MSG="Ubuntu updates:
-(If there are updates, do not forget to update aos-Gateway as well.)
+   local FIRST_CHAR="${RESULT:0:1}"
+      
+   if [ "$FIRST_CHAR" != "0" ]; then
+      local MSG="$RESULT
+Please update aos-Gateway and aos-Workstation:
+sudo apt-get update && sudo apt-get dist-upgrade"
+      echo "$MSG"
+      output "--error" "WARNING" "$MSG"
+      return
+   fi
+   
+   local MSG="Ubuntu is up to date.
 $RESULT"
-
    echo "$MSG"
    output "--info" "Info" "$MSG"
 }
@@ -521,7 +549,7 @@ download_aos_news() {
 aos_news.asc "$AOS_HOMEPAGE/aos_news.asc" || DOWNLOAD_NEWS_SUCCESS="0"
 
    # Uncomment the following three lines to test what happens
-   # whenn verification fails.
+   # when verification fails.
    #ip="$GATEWAY_IP" port="$SOCKS_PORT_AOS_NEWS" uwt \
 #/usr/bin/wget $TORCHECK_VERBOSE --output-document \
 #aos_news.asc "$AOS_HOMEPAGE" || DOWNLOAD_NEWS_SUCCESS="0"
