fix

diff --git a/release/upload_whonix_news_v3 b/release/upload_whonix_news_v3
--- a/release/upload_whonix_news_v3
+++ b/release/upload_whonix_news_v3
@@ -32,15 +32,17 @@ export VMNAME="internalrun"
 
 source variables
 
-mkdir --parents "$WHONIX_BINARY"/news_v3
+if [ "$(id -u)" = "0" ]; then
+   echo "${red}${bold}ERROR: Do not run this script as root!${reset}"
+   exit 1
+fi
 
-## Reading ./release/whonix_news, substitute the $WHONIX_BUILD_WHONIX_VERSION variable in ./release/whonix_news
-## with the actual WHONIX_BUILD_WHONIX_VERSION and storing it as ../whonix_binary/whonix_news.
-##
-## Thanks to:
-## http://superuser.com/questions/235738/how-do-i-substitute-environment-variables-when-i-ouput-a-file
+rm --force --recursive "$WHONIX_BINARY/news_v3_temp"
+rm --force --recursive "$WHONIX_BINARY/news_v3"
+mkdir --parents "$WHONIX_BINARY/news_v3_temp"
+mkdir --parents "$WHONIX_BINARY/news_v3"
 
-for i in "$WHONIX_SOURCE_FOLDER"/release/news/*; do
+for i in "$WHONIX_SOURCE_FOLDER/release/news/"*; do
    if [ -f "$i" ]; then
       ## If the last character is a ~, ignore that file,
       ## because it was created by some editor,
@@ -52,25 +54,23 @@ for i in "$WHONIX_SOURCE_FOLDER"/release/news/*; do
 
    filename="$(basename "$i")"
 
-   cp "$i" "$WHONIX_BINARY"/news_v3/"$filename"
-   sync
+   cp "$i" "$WHONIX_BINARY/news_v3_temp/$filename"
 
    ## Debugging.
-   cat "$WHONIX_BINARY"/news_v3/"$filename"
+   cat "$WHONIX_BINARY/news_v3_temp/$filename"
 
 done
 
-rm --force "$WHONIX_BINARY"/news_v3/.directory
-rm --force "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz
-rm --force "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc
+rm --force "$WHONIX_BINARY/news_v3_temp/.directory"
+
 sync
 
-tar -zcvpf "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz -C "$WHONIX_BINARY"/news_v3 .
+tar -zcvpf "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" -C "$WHONIX_BINARY/news_v3_temp" .
 sync
 
-gpg --detach-sign --armor --yes "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz
+gpg --detach-sign --armor --yes "$WHONIX_BINARY/news_v3/whonix_news.tar.gz"
 sync
-gpg --verify "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc
+gpg --verify "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc"
 
 true "INFO $0: Please press any key to continue with --dry-run."
 
@@ -83,9 +83,9 @@ rsync \
    --progress \
    --verbose \
    --rsh ssh \
-   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc \
-   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz \
-   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/
+   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc" \
+   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" \
+   "adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/"
 
 true "INFO $0: Please press any key to continue to upload."
 
@@ -97,6 +97,6 @@ rsync \
    --progress \
    --verbose \
    --rsh ssh \
-   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz.asc \
-   "$WHONIX_BINARY"/news_v3/whonix_news.tar.gz \
-   adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/
+   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz.asc" \
+   "$WHONIX_BINARY/news_v3/whonix_news.tar.gz" \
+   "adrelanos,whonixdevelopermetafiles@frs.sourceforge.net:/home/frs/project/whonixdevelopermetafiles/internal/news_v3/"
