Whonix-Gateway: Added First Time Connection Wizard.

diff --git a/whonix_gateway/usr/local/bin/ft_m_1 b/whonix_gateway/usr/local/bin/ft_m_1
--- a/whonix_gateway/usr/local/bin/ft_m_1
+++ b/whonix_gateway/usr/local/bin/ft_m_1
@@ -1,7 +1,80 @@
 #!/bin/bash
 
-MSG="Tor tries to prevent attackers from learning what destination websites you connect to. However, by default, it does not prevent somebody watching your Internet traffic from learning that you are using Tor. If this matters to you, you can reduce this risk by configuring Tor to use a Tor bridge relay rather than connecting directly to the public Tor network. Ultimately the best protection is a social approach: the more Tor users there are near you and the more diverse their interests, the less dangerous it will be that you are one of them. Convince other people to use Tor, too!"
+error_handler() {
+   local MSG="\
+###########################################################
+## Something went wrong. Please report this bug!
+##
+## BASH_COMMAND: $BASH_COMMAND
+###########################################################\
+"
+   echo "$MSG"
+   exit 1
+} 
+
+trap "error_handler" ERR INT TERM
+
+## root check
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+fi
+
+## sanity checks
+which dialog
+which ed
+which service
+if [ ! -e "/etc/tor/torrc" ]; then
+   error "/etc/tor/torrc does not exist. Please report this bug!"
+   exit 1
+fi
+
+MSG="
+Tor tries to prevent attackers from learning what destination websites you connect to. However, by default, it does not prevent somebody watching your Internet traffic from learning that you are using Tor. If this matters to you, you can reduce this risk by configuring Tor to use a Tor bridge relay rather than connecting directly to the public Tor network. Ultimately the best protection is a social approach: the more Tor users there are near you and the more diverse their interests, the less dangerous it will be that you are one of them. Convince other people to use Tor, too!
+
+Enable Tor and connect to the public Tor network?
+"
 
 TITLE="Connect to the public Tor network."
 
+trap "" ERR INT TERM
+dialog --title "$TITLE" --yesno "$MSG" 640 480
+returncode=$?
+trap "error_handler" ERR INT TERM
+
+if [ ! "$returncode" = "0" ]; then
+   ## Back to main menu.
+   whonixsetup
+   exit 0
+fi
+
+## Check if Tor was already disabled.
+## This is to prevent getting a /etc/tor/torrc with entry
+## looking like ####DisableNetwork 1 (if the user chooses
+## this option multiple times).
+while read LINE; do
+   if [ "$LINE" = 'DisableNetwork 1' ]; then
+      service tor reload 
+      dialog --title "Success!" --msgbox "\"DisableNetwork 1\" was already commented out in /etc/tor/torrc.
+So Tor should now be activated." 640 480
+      exit 0
+   fi
+done < "/etc/tor/torrc"
+
+## Comment out DisableNetwork 1 in /etc/tor/torrc
+ed -s /etc/tor/torrc <<< $',s/#DisableNetwork 1/DisableNetwork 1/g\nw'
+
+service tor reload
+
+MSG="
+Tor has been activated.
+"
+
+TITLE="Success!"
+
+trap "" ERR INT TERM
 dialog --title "$TITLE" --msgbox "$MSG" 640 480
+trap "error_handler" ERR INT TERM
+
+exit 0
+
diff --git a/whonix_gateway/usr/local/bin/ft_m_8 b/whonix_gateway/usr/local/bin/ft_m_8
--- a/whonix_gateway/usr/local/bin/ft_m_8
+++ b/whonix_gateway/usr/local/bin/ft_m_8
@@ -1,8 +1,70 @@
 #!/bin/bash
 
-MSG=""
+error_handler() {
+   local MSG="\
+###########################################################
+## Something went wrong. Please report this bug!
+##
+## BASH_COMMAND: $BASH_COMMAND
+###########################################################\
+"
+   echo "$MSG"
+   exit 1
+} 
+
+trap "error_handler" ERR INT TERM
+
+## root check
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+fi
+
+## sanity checks
+which dialog
+which ed
+which service
+if [ ! -e "/etc/tor/torrc" ]; then
+   error "/etc/tor/torrc does not exist. Please report this bug!"
+   exit 1
+fi
+
+MSG="
+Do you want to disable Tor?
+"
 
 TITLE="Disable Tor."
 
-dialog --title "$TITLE" --msgbox "$MSG" 640 480
+trap "" ERR INT TERM
+dialog --title "$TITLE" --yesno "$MSG" 640 480
+returncode=$?
+trap "error_handler" ERR INT TERM
 
+if [ ! "$returncode" = "0" ]; then
+   ## Back to main menu.
+   whonixsetup
+   exit 0
+fi
+
+## Check if Tor was already disabled.
+## This is to prevent getting a /etc/tor/torrc with entry
+## looking like ####DisableNetwork 1 (if the user chooses
+## this option multiple times).
+while read LINE; do
+   if [ "$LINE" = "#DisableNetwork 1" ]; then
+      service tor reload 
+      dialog --title "Success!" --msgbox "\"DisableNetwork 1\" was already set in /etc/tor/torrc.
+So Tor should now be disabled." 640 480
+      exit 0
+   fi
+done < "/etc/tor/torrc"
+
+ed -s /etc/tor/torrc <<< $',s/\DisableNetwork 1/#DisableNetwork 1/g\nw'
+
+service tor reload
+
+trap "" ERR INT TERM
+dialog --title "Success!" --msgbox "Tor has been deactivated." 640 480
+trap "error_handler" ERR INT TERM
+
+exit 0
diff --git a/whonix_gateway/usr/local/bin/whonixsetup b/whonix_gateway/usr/local/bin/whonixsetup
--- a/whonix_gateway/usr/local/bin/whonixsetup
+++ b/whonix_gateway/usr/local/bin/whonixsetup
@@ -4,12 +4,40 @@
 #set -x
 #export PATH=$PATH:/home/user/Whonix/whonix_gateway/usr/local/bin/
 
-./ft_main
+error_handler() {
+   local MSG="\
+###########################################################
+## Something went wrong. Please report this bug!
+##
+## BASH_COMMAND: $BASH_COMMAND
+###########################################################\
+"
+   echo "$MSG"
+   exit 1
+} 
 
-## get return code
+trap "error_handler" ERR INT TERM
+
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+fi
+
+## sanity tests
+which ft_main
+
+trap "" ERR INT TERM
+ft_main
 returncode="$?"
+trap "error_handler" ERR INT TERM
 
 ## if the cancel button gets pressed, returncode will be 0
 
-./ft_m_$returncode
+trap "" ERR INT TERM
+ft_m_$returncode
+trap "error_handler" ERR INT TERM
+
+echo "You can always enter the setup again, by starting: whonixsetup"
+
+exit 0
 
