work on #113

diff --git a/whonix_shared/usr/lib/whonix/first_boot_installer b/whonix_shared/usr/lib/whonix/first_boot_installer
--- a/whonix_shared/usr/lib/whonix/first_boot_installer
+++ b/whonix_shared/usr/lib/whonix/first_boot_installer
@@ -4,17 +4,22 @@
 # Copyright (C) 2012 - 2013 adrelanos <adrelanos at riseup dot net>
 # See the file COPYING for copying conditions.
 
-## TODO: root_check
-
 ## TODO: Installer log.
 
 maybe_run() {
    if [ ! -x "$1" ]; then
-      true "$1 does not exist. Either the package isn't installed, that script does not provide that script or else..."
+      true "$1 does not exist. Either the package is not installed, that script does not provide that script or else..."
       return 0
    fi
    $1 $2
 }
+
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+else
+    true "INFO: Script running as root."
+fi
 
 ## non-deterministic [1]
 ## /var/cache/fontconfig folder
@@ -47,23 +52,29 @@ maybe_run /var/lib/dpkg/info/man-db.postinst configure
 maybe_run /var/lib/dpkg/info/xml-core.preinst install
 maybe_run /var/lib/dpkg/info/xml-core.postinst configure
 
-## non-deterministic [5]
-## /etc/xml/sgml-data
-## /etc/xml/sgml-data.old
-maybe_run /var/lib/dpkg/info/sgml-data.preinst install
-maybe_run /var/lib/dpkg/info/sgml-data.postinst configure
-
 ## non-deterministic [6]
 ## /var/lib/sgml-base/supercatalog
 ## /var/lib/sgml-base/supercatalog.old
 maybe_run /var/lib/dpkg/info/sgml-base.preinst install
 maybe_run /var/lib/dpkg/info/sgml-base.postinst configure
 
+## non-deterministic [5]
+## /etc/xml/sgml-data
+## /etc/xml/sgml-data.old
+maybe_run /var/lib/dpkg/info/sgml-data.preinst install
+maybe_run /var/lib/dpkg/info/sgml-data.postinst configure
+
 ## non-deterministic [7]
 ## /etc/xml/docbook-xml.xml
 ## /etc/xml/docbook-xml.xml.old
 maybe_run /var/lib/dpkg/info/docbook-xml.preinst install
 maybe_run /var/lib/dpkg/info/docbook-xml.postinst configure
+
+## non-deterministic [14]
+## /etc/xml/docbook-xsl.xml
+## /var/lib/xml-core/docbook-xsl
+maybe_run /var/lib/dpkg/info/docbook-xsl.preinst install
+maybe_run /var/lib/dpkg/info/docbook-xsl.postinst configure
 
 ## non-deterministic [8]
 ## /usr/share/info/dir file
