whonixcheck: whonix_shared/etc/init.d/whonixcheckd: on stop, give whonixcheck time to gracefully shut down so it can close any still eventually open progress bars whonix_shared/usr/lib/whonix/process_killer_helper: implement error_handler if there is none already whonix_shared/usr/lib/whonix/whonixcheck/75_cleanup: fix, also close "waiting for package manager" waiting progress bar, it whonixcheck gets shut down by its init script

diff --git a/whonix_shared/usr/lib/whonix/process_killer_helper b/whonix_shared/usr/lib/whonix/process_killer_helper
--- a/whonix_shared/usr/lib/whonix/process_killer_helper
+++ b/whonix_shared/usr/lib/whonix/process_killer_helper
@@ -1,7 +1,15 @@
 #!/bin/bash
 
 process_killer_helper() {
-   trap "error_handler" ERR
+   if [ "$(type -t error_handler)" = "function" ]; then
+      ## Error handler already implemented. Using it.
+      trap "error_handler" ERR
+   else
+      ## No error available yet. Implementing one.
+      error_handler() {
+         echo "Error detected! BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code"
+      }
+   fi
 
    if [ "$lastpid" = "" ]; then
       return 0
