Re-implemented uwt and dummytor using config-package-dev instead of custom dpkg-diversions. Breaks compatibly with Whonix 7.

diff --git a/whonix_shared/usr/lib/whonix/uwtwrapper b/whonix_shared/usr/lib/whonix/uwtwrapper
--- a/whonix_shared/usr/lib/whonix/uwtwrapper
+++ b/whonix_shared/usr/lib/whonix/uwtwrapper
@@ -4,7 +4,7 @@
 ## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
-## Whonix /usr/bin/$SCRIPTNAME uwt wrapper.
+## Whonix $uwtwrapper_parent uwt wrapper.
 
 ## If you want to enable/disable uwt and/or privacy
 ## globally or for certain applications, see /etc/whonix.d/.
@@ -23,24 +23,25 @@ set -o pipefail
 SCRIPTNAME="$(basename $0)"
 
 error_handler() {
-echo "
+   echo "
 ## uwtwrapper BUG.
 ## SCRIPTNAME: $SCRIPTNAME
+## uwtwrapper_parent: $uwtwrapper_parent
 ## BASH_COMMAND: $BASH_COMMAND
 ## Please report this BUG!
 "
-exit 1
+   exit 1
 }
 
 trap "error_handler" ERR
 
 sanity_tests_general() {
-   if [ ! -e "/usr/bin/$SCRIPTNAME.real" ]; then
-      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.real does not exist."
+   if [ ! -e "$uwtwrapper_parent.whonix-orig" ]; then
+      echo "$SCRIPTNAME uwt wrapper ERROR: $uwtwrapper_parent.whonix-orig does not exist."
       exit 1
    fi
-   if [ ! -x "/usr/bin/$SCRIPTNAME.real" ]; then
-      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.real is not executable."
+   if [ ! -x "$uwtwrapper_parent.whonix-orig" ]; then
+      echo "$SCRIPTNAME uwt wrapper ERROR: $uwtwrapper_parent.whonix-orig is not executable."
       exit 1
    fi
 }
@@ -103,16 +104,9 @@ for i in /etc/whonix.d/*; do
    fi
 done
 
-## Since application names sometimes contains "-" and bash variables
-## may not include "-", we have to remove "-" from the script name.
-SCRIPTNAME_CLEANED="$(echo "$SCRIPTNAME" | sed 's/-//g')"
+port=${uwtport["$uwtwrapper_parent"]}
 
-temp="uwtport_$SCRIPTNAME_CLEANED"
-port="${!temp}"
-
-temp="timeprivacy_$SCRIPTNAME"
-
-if [ "${!temp}" = "1" ]; then
+if [ "${timeprivacy["$uwtwrapper_parent"]}" = "1" ]; then
    fake_time="faketime"
    privacy_time="$("time_privacy" -f "/tmp/timeprivacy_$SCRIPTNAME_CLEANED")"
 else
@@ -125,57 +119,55 @@ else
    fi
 fi
 
-## Using "|| { ret="$?" ; true; };" to prevent invoking error_handler in case
-## the executed application returned a non-zero value.
+## Using "|| { exit_code="$?" ; true; };" to prevent invoking error_handler in case
+## the executed application exits with a non-zero value.
 ##
 ## Bash syntax: command1 || command2
 ##
-## Setting default ret="0" beforehand, because
-## command2 does only get executed, if command1 return non-zero.
-## So in case it's zero, the default return value must be already set.
+## Setting default exit_code="0" beforehand, because
+## command2 does only get executed, if command1 exits non-zero.
+## So in case it's zero, the default exit_code value must be already set.
 
 if [ "$uwtwrapper_global" = "0" ]; then
    if [ "$fake_time" = "faketime" ]; then
       sanity_tests_general
       sanity_tests_timeprivacy
-      ret="0"
-      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$fake_time" "$privacy_time" "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    else
       sanity_tests_general
-      ret="0"
-      exec "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    fi
-   exit "$ret"
+   exit "$exit_code"
 fi
 
-temp="uwtwrapper_$SCRIPTNAME_CLEANED"
-
-if [ "${!temp}" = "0" ]; then
+if [ "${uwtwrapper["$uwtwrapper_parent"]}" = "0" ]; then
    if [ "$fake_time" = "faketime" ]; then
       sanity_tests_general
       sanity_tests_timeprivacy
-      ret="0"
-      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$fake_time" "$privacy_time" "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    else
       sanity_tests_general
-      ret="0"
-      exec "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    fi
-   exit "$ret"
+   exit "$exit_code"
 fi
 
 if [ "$fake_time" = "faketime" ]; then
    sanity_tests_general
    sanity_tests_uwt
    sanity_tests_timeprivacy
-   ret="0"
-   exec "$fake_time" "$privacy_time" "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+   exit_code="0"
+   exec "$fake_time" "$privacy_time" "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
 else
    sanity_tests_general
    sanity_tests_uwt
-   ret="0"
-   exec "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+   exit_code="0"
+   exec "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "$uwtwrapper_parent.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
 fi
-exit "$ret"
+exit "$exit_code"
 
-## End of Whonix /usr/bin/$SCRIPTNAME uwt wrapper.
+## End of Whonix $uwtwrapper_parent uwt wrapper.
