whonix_shared/usr/local/bin/whonixcheck-scripts/67_check_clock: using sudo service xxx status instead of checking the status files directly

diff --git a/whonix_shared/usr/local/bin/whonixcheck-scripts/67_check_clock b/whonix_shared/usr/local/bin/whonixcheck-scripts/67_check_clock
--- a/whonix_shared/usr/local/bin/whonixcheck-scripts/67_check_clock
+++ b/whonix_shared/usr/local/bin/whonixcheck-scripts/67_check_clock
@@ -1,25 +1,25 @@
 check_bootclockrandomization() {
-   if [ -e "/var/run/bootclockrandomization/fail" ]; then
-      ## fail
-      local MSG="bootclockrandomization failed. Please report this bug!
-$(cat /var/log/bootclockrandomization.log)"
-      output "--error" "ERROR" "$MSG" "both"      
-   else
-      ## ok
+   sudo service bootclockrandomization status
+   local returncode="$?"
+   
+   if [ "$returncode" = "0" ]; then
       local MSG="bootclockrandomization success."
       #output "--info" "Info" "$MSG" "both"
-      return      
+   else
+      local MSG="bootclockrandomization failed. Please report this bug!
+$(cat /var/log/bootclockrandomization.log)"
+      output "--error" "ERROR" "$MSG" "both"        
    fi
 }
 
 check_timesanitycheck() {
-   if [ -e "/var/run/timesanitycheck/success" ]; then
-      # ok
+   sudo service timesanitycheck status
+   local returncode="$?"
+   
+   if [ "$returncode" = "0" ]; then
       local MSG="timesanitycheck success."
       #output "--info" "Info" "$MSG" "both"
-      return
    else
-      ## fail
       local MSG="timesanitycheck failed. Please report this bug!
 $(cat /var/log/timesanitycheck.log)"
       output "--error" "ERROR" "$MSG" "both"  
