whonix_shared/usr/local/bin/whonixcheck-scripts/70_check-htpdate: spaces

diff --git a/whonix_shared/usr/local/bin/whonixcheck-scripts/70_check-htpdate b/whonix_shared/usr/local/bin/whonixcheck-scripts/70_check-htpdate
--- a/whonix_shared/usr/local/bin/whonixcheck-scripts/70_check-htpdate
+++ b/whonix_shared/usr/local/bin/whonixcheck-scripts/70_check-htpdate
@@ -1,23 +1,23 @@
 check_htpdate() {
-  trap "error_handler" ERR INT TERM
+   trap "error_handler" ERR INT TERM
 
-  let "PROGRESS=$PROGRESS+1" || true
-  progress_bar $PROGRESS
+   let "PROGRESS=$PROGRESS+1" || true
+   progress_bar $PROGRESS
 
-  local pid_file="/var/run/htpdate/pid"
-  local done_file="/var/run/htpdate/done"
-  local success_file="/var/run/htpdate/success"
+   local pid_file="/var/run/htpdate/pid"
+   local done_file="/var/run/htpdate/done"
+   local success_file="/var/run/htpdate/success"
 
-  TIME_END="`date +%s`"
-  TIME_DIFF="`expr "$TIME_END" - "$TIME_START"`" || true
-  WAIT_MIN="60"
+   TIME_END="`date +%s`"
+   TIME_DIFF="`expr "$TIME_END" - "$TIME_START"`" || true
+   WAIT_MIN="60"
 
-  #echo "check_htpdate debug info: expr $WAIT_MIN - $TIME_DIFF"
-  WAIT_RESULT="`expr "$WAIT_MIN" - "$TIME_DIFF"`" || true
-  #echo "check_htpdate debug info: WAIT_RESULT: $WAIT_RESULT"
+   #echo "check_htpdate debug info: expr $WAIT_MIN - $TIME_DIFF"
+   WAIT_RESULT="`expr "$WAIT_MIN" - "$TIME_DIFF"`" || true
+   #echo "check_htpdate debug info: WAIT_RESULT: $WAIT_RESULT"
 
-  if [ ! -f "$pid_file" ]; then
-    local MSG='Network Time Synchronization failed!!! pid_file does not exist. Please report this bug!
+   if [ ! -f "$pid_file" ]; then
+      local MSG='Network Time Synchronization failed!!! pid_file does not exist. Please report this bug!
 See logfile: tail -f -n 20 /var/log/htpdate.log
 See status files: cd /var/run/htpdate && dir
 Try again: Start menu -> Applications -> System -> Whonix Timesync
@@ -25,25 +25,25 @@ Try again: Start menu -> Applications -> System -> Whonix Timesync
 Last resort: manually set the clock! (In UTC!):
              sudo su
              date -s "17 FEB 2012 24:00:00" && hwclock -w'
-    echo "$MSG"
-    #echo "System clock is set to: `date`"
-    output "--error" "ERROR" "$MSG"
-    return
-  fi
+      echo "$MSG"
+      #echo "System clock is set to: `date`"
+      output "--error" "ERROR" "$MSG"
+      return
+   fi
 
-  if [ -f "$success_file" ]; then
-    local SUCCESS_TIME="`date -r "$success_file"`" 
-    local MSG="Last run (on "$SUCCESS_TIME") of Network Time Synchronization (timesync) successful."
-    echo "$MSG"
-    #echo "System clock is set to: `date`"
-    output "--info" "Info" "$MSG"
-    return
-  fi
-  
-  if [ -f "$done_file" ]; then
-    ## Done but no success. This should rarely happen. Only in case the internet connection
-    ## was done at this point. We checked internet connection some moments ago.
-    local MSG='Network Time Synchronization done but no success!!!
+   if [ -f "$success_file" ]; then
+      local SUCCESS_TIME="`date -r "$success_file"`" 
+      local MSG="Last run (on "$SUCCESS_TIME") of Network Time Synchronization (timesync) successful."
+      echo "$MSG"
+      #echo "System clock is set to: `date`"
+      output "--info" "Info" "$MSG"
+      return
+   fi
+   
+   if [ -f "$done_file" ]; then
+      ## Done but no success. This should rarely happen. Only in case the internet connection
+      ## was done at this point. We checked internet connection some moments ago.
+      local MSG='Network Time Synchronization done but no success!!!
 Is your internet connection down?
 Test your internet connection: Start menu -> Applications -> System -> Whonixcheck
                                or in Terminal: whonixcheck
@@ -56,22 +56,22 @@ Try again: Start menu -> Applications -> System -> Whonix Timesync
 Last resort: manually set the clock! (In UTC!):
              sudo su
              date -s "17 FEB 2012 24:00:00" && hwclock -w'
-    echo "$MSG"
-    #echo "System clock is set to: `date`"
-    output "--error" "ERROR" "$MSG"
-    return
-  fi
+      echo "$MSG"
+      #echo "System clock is set to: `date`"
+      output "--error" "ERROR" "$MSG"
+      return
+   fi
 
-  #echo "check_htpdate debug info: WAIT_RESULT: $WAIT_RESULT"
+   #echo "check_htpdate debug info: WAIT_RESULT: $WAIT_RESULT"
 
-  if [ $WAIT_RESULT -gt 0 ]; then
-    #echo "check_htpdate debug info: Not done. Waiting up to $WAIT_RESULT more seconds."
-    sleep 5
-    check_htpdate
-    return
-  fi
+   if [ $WAIT_RESULT -gt 0 ]; then
+      #echo "check_htpdate debug info: Not done. Waiting up to $WAIT_RESULT more seconds."
+      sleep 5
+      check_htpdate
+      return
+   fi
 
-  local MSG='Network Time Synchronization failed!!!
+   local MSG='Network Time Synchronization failed!!!
 See logfile: tail -f -n 20 /var/log/htpdate.log
 See status files: cd /var/run/htpdate && dir
 Try again: Start menu -> Applications -> System -> Whonix Timesync
@@ -79,10 +79,10 @@ Try again: Start menu -> Applications -> System -> Whonix Timesync
 Last resort: manually set the clock! (In UTC!):
              sudo su
              date -s "17 FEB 2012 24:00:00" && hwclock -w'
-  echo "$MSG"
-  #echo "System clock is set to: `date`"
-  output "--error" "ERROR" "$MSG"
-  return
+   echo "$MSG"
+   #echo "System clock is set to: `date`"
+   output "--error" "ERROR" "$MSG"
+   return
 }
 
  
