whonixsetup: Working around another bug in Tor. When starting Tor fails, it does not return a non-zero return code.

diff --git a/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_1 b/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_1
--- a/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_1
+++ b/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_1
@@ -115,6 +115,13 @@ if [ ! "$returncode" = "0" ]; then
    sleep 1
 fi
 
+## Working around another bug in Tor.
+## When starting Tor fails, it does not return a non-zero return code.
+returncode=0
+service tor status || { returncode=$? ; true; };
+sync
+sleep 1
+
 if [ ! "$returncode" = "0" ]; then
 
    TITLE="Error!"
