renamed: whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_8 -> whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2 renamed: whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2 -> whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_8

diff --git a/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2 b/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2
--- a/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2
+++ b/whonix_gateway/usr/lib/whonix/whonixsetup/ft_m_2
@@ -1,42 +1,113 @@
 #!/bin/bash
 
-#set -x
+set -x
 
-MSG='
-(You can scroll down using the arrow key.)
+error_handler() {
+   local MSG="\
+###########################################################
+## Something went wrong. Please report this bug!
+##
+## BASH_COMMAND: $BASH_COMMAND
+###########################################################\
+"
+   echo "$MSG"
+   exit 1
+} 
 
-Some Internet Service Providers prevent users from accessing the Tor network by blocking connections to known relays. "Bridge relays" help these users access Tor by not being listed in the same public directories as normal relays. Less sophisticated censors have trouble censoring all of them.
+trap "error_handler" ERR
 
-Sophisticated censors can only be circumvented with private obfuscated bridges. Someone you trust must run a bridge configured with obfsproxy (to help avoid detection) and the option "PublishServerDescriptor 0" (to not be listed by The Tor Project). However, since even private obfuscated bridges can ultimately be detected, Whonix does NOT recommend using Tor where its detection could result in significant harm.
+## root check
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+fi
 
+stop_tor() {
+      returncode=0
+      service tor status || { returncode=$? ; true; };
+      sync
+      sleep 1
+      
+      if [ "$returncode" = "0" ]; then      
+         dialog --title "Info" --msgbox 'Tor still running. Stopping it now...' 640 480      
+      
+         returncode=0
+         service tor stop || { returncode=$? ; true; };
+         sync
+         sleep 1
+         
+         dialog --title "Info" --msgbox 'Stopped Tor.' 640 480
+      else
+         dialog --title "Info" --msgbox 'Tor was already stopped.' 640 480
+      fi
+}
 
-Finding Bridges
----------------
+MSG="
+Do you want to disable Tor?
+"
 
-You can find the IP address of public bridges at:
-https://bridges.torproject.org/bridges
+TITLE="Disable Tor."
 
-If you can not reach the URL, send an email (from a gmail.com or yahoo.com account only) to bridges@torproject.org with "get bridges" in the message body.
+returncode=0
+dialog --title "$TITLE" --yesno "$MSG" 640 480 || { returncode=$? ; true; };
 
-Whonix recommends using "bridge obfs3" IP addresses only.
+if [ ! "$returncode" = "0" ]; then
+   ## Back to main menu.
+   whonixsetup
+   exit 0
+fi
 
+## Check if Tor was already disabled.
+## This is to prevent getting a /etc/tor/torrc with entry
+## looking like ####DisableNetwork 1 (if the user chooses
+## this option multiple times).
+while read LINE; do
+   if [ "$LINE" = "DisableNetwork 1" ]; then      
+      dialog --title "Success!" --msgbox '"DisableNetwork 1" was already set in /etc/tor/torrc.
+So Tor should now be disabled.
 
-Configure Whonix to Use Bridges
--------------------------------
+whonixsetup really only deactivates Tor by commenting in "DisableNetwork 1" in /etc/tor/torrc.
+Running it multiple times in a row archives nothing.
+In case of network problems, this is probably not the cause.
+You can confirm that by manually checking if "DisableNetwork 1" has been commented in /etc/tor/torrc.
+' 640 480
 
-Press enter to close this message, then cancel the connection wizard by using Cancel button in the main menu. You must manually add the bridge(s) IP address to /etc/tor/torrc. Comments and examples in that file will help you through the process. After you have finished, restart the First Time Connection Wizard.
+      dialog --title "Info" --msgbox 'Checking if Tor is still running and stopping it if necessary...' 640 480
 
-You can open /etc/tor/torrc in the terminal:
+      stop_tor
+      ## Signal for whonixsetup to break the while loop. 
+      exit 1
+   fi
+done < "/etc/tor/torrc"
 
-    sudo nano /etc/tor/torrc
+dialog --title "Info" --msgbox 'Trying to disable Tor...
 
-Or, if you are using a graphical Whonix-Gateway:
+Technically speaking, this will comment in "DisableNetwork 1" in /etc/tor/torrc.
+' 640 480
 
-    Start Menu -> Applications -> /etc/tor/torrc
-'
+returncode=0
+ed -s /etc/tor/torrc <<< $',s/\#DisableNetwork 1/DisableNetwork 1/g\nw' || { returncode=$? ; true; };
+sync
 
-TITLE="Tor is censored in my area."
+if [ "$returncode" = "0" ]; then
+   stop_tor
+   ## Signal for whonixsetup to break the while loop.
+   exit 1
 
-dialog --title "$TITLE" --msgbox "$MSG" 640 480
+   dialog --title "Success!" --msgbox 'Tor has been deactivated.
 
-exit 0
+(Technically speaking, whonixsetup deactivated Tor by commenting in "DisableNetwork 1" in /etc/tor/torrc.)' 640 480
+else
+   dialog --title "ERROR!" --msgbox 'Tor could not be deactivated. Please report this bug!
+
+(Technically speaking, whonixsetup could not deactivate Tor by commenting in "DisableNetwork 1" in /etc/tor/torrc (ed failed).)' 640 480
+
+   dialog --title "WARNING" --msgbox 'Will at least stop Tor...
+   
+Warning: Since Tor could not be deactivated in /etc/tor/torrc, Tor will be reconnect, next time you reboot or restart Tor. You are advised to manually add "DisableNetwork 1" in /etc/tor/torrc and to run "sudo service tor stop" to ensure, that Tor will not start, if that is what you want.' 640 480
+
+   stop_tor
+   ## Signal for whonixsetup to break the while loop.
+   exit 1
+fi
+
