work on #113

diff --git a/help-steps/analyze_image b/help-steps/analyze_image
--- a/help-steps/analyze_image
+++ b/help-steps/analyze_image
@@ -108,12 +108,14 @@ parse_cmd() {
        esac
    done
 
-   if [ "$ova_file" = "baremetal" ]; then
-      ## A bit of a hack.
-      BARE_METAL="1"
-   elif [ ! -f "$ova_file" ]; then
-      echo "ERROR: ova_file $ova_file does not exist!"
-      exit 1
+   if [ ! -f "$ova_file" ]; then
+      if [ "$ova_file" = "baremetal" ]; then
+         ## A bit of a hack.
+         BARE_METAL="1"
+      else
+         echo "ERROR: ova_file $ova_file does not exist!"
+         exit 1
+      fi
    fi
 
    if [ "$report_file" = "" ]; then
