sanity test

diff --git a/help-steps/cowbuilder_repo_download_chroot_script b/help-steps/cowbuilder_repo_download_chroot_script
--- a/help-steps/cowbuilder_repo_download_chroot_script
+++ b/help-steps/cowbuilder_repo_download_chroot_script
@@ -18,6 +18,11 @@ if [ -f "/tmp/tpo_repo/repo_signing_key.asc" ]; then
    apt-key --keyring "/etc/apt/trusted.gpg.d/newer.gpg" add "/tmp/tpo_repo/repo_signing_key.asc"
 fi
 
+if [ "$temp_newer_packages" = "" ]; then
+   echo "ERROR $0: temp_newer_packages is empty!"
+   exit 1
+fi
+
 pushd "$temp_newer_packages"
 
 ## Use dpkg multiarch so we can download other architectures than the build host's one using apt-get.
