port to sequoia-pgp

diff --git a/help-steps/git_sanity_test b/help-steps/git_sanity_test
--- a/help-steps/git_sanity_test
+++ b/help-steps/git_sanity_test
@@ -33,66 +33,74 @@ fi
 
 ## NOTE: No longer in use.
 ## TODO: Remove?
-import_keys() {
-  ## GnuPG ('gpg') required a local keystore.
-  ## sequoia-gpg ('sq') does not require a local keystore.
-  ##
-  ## However, 'git' is hardcoded to use 'gpg' and has no native
-  ## Sequoia-PGP ('sq') support. Therefore at best 'git' can be configured to use
-  ## use 'gpg-sq' (using 'sequoia-chameleon-gnupg') either using:
-  ## * A) Git configuration file; or
-  ## * B) Debian package 'gpg-from-sq'.
-  ## 'gpg' (or 'gpg-sq') however requires a 'gpg' local keystore.
-  ## Therefore signing public key import into the 'gpg' local keystore still required.
-
-  local key_index derivative_signing_key_fingerprint_list derivative_signing_public_key_item derivative_signing_key_fingerprint_item
-
-  for key_index in "${!derivative_signing_public_key_list[@]}"; do
-    readarray -t derivative_signing_key_fingerprint_list <<< "${derivative_verification_key_fingerprint_group_list[key_index]}"
-    derivative_signing_public_key_item="${derivative_signing_public_key_list[key_index]}"
-
-    for derivative_signing_key_fingerprint_item in "${derivative_signing_key_fingerprint_list[@]}"; do
-      if $gpg_bin --quiet --list-keys -- "${derivative_signing_key_fingerprint_item}" &>/dev/null; then
-        true "INFO: key already imported."
-      else
-        true "INFO: key not yet already imported. Importing..."
-        test -r "${derivative_signing_public_key_item}"
-        sq --keyring="${derivative_signing_public_key_item}" --cert-store=none cert list --gossip
-        $gpg_bin --import -- "${derivative_signing_public_key_item}"
-        $gpg_bin --check-sigs -- "${derivative_signing_key_fingerprint_item}"
-        break
-      fi
-    done
-  done
-}
+# import_keys() {
+#   ## GnuPG ('gpg') required a local keystore.
+#   ## sequoia-gpg ('sq') does not require a local keystore.
+#   ##
+#   ## However, 'git' is hardcoded to use 'gpg' and has no native
+#   ## Sequoia-PGP ('sq') support. Therefore at best 'git' can be configured to use
+#   ## use 'gpg-sq' (using 'sequoia-chameleon-gnupg') either using:
+#   ## * A) Git configuration file; or
+#   ## * B) Debian package 'gpg-from-sq'.
+#   ## 'gpg' (or 'gpg-sq') however requires a 'gpg' local keystore.
+#   ## Therefore signing public key import into the 'gpg' local keystore still required.
+#
+#   local key_index derivative_signing_key_fingerprint_list derivative_signing_public_key_item derivative_signing_key_fingerprint_item
+#
+#   for key_index in "${!derivative_signing_public_key_list[@]}"; do
+#     readarray -t derivative_signing_key_fingerprint_list <<< "${derivative_verification_key_fingerprint_group_list[key_index]}"
+#     derivative_signing_public_key_item="${derivative_signing_public_key_list[key_index]}"
+#
+#     for derivative_signing_key_fingerprint_item in "${derivative_signing_key_fingerprint_list[@]}"; do
+#       if $gpg_bin --quiet --list-keys -- "${derivative_signing_key_fingerprint_item}" &>/dev/null; then
+#         true "INFO: key already imported."
+#       else
+#         true "INFO: key not yet already imported. Importing..."
+#         test -r "${derivative_signing_public_key_item}"
+#         sq --keyring="${derivative_signing_public_key_item}" --cert-store=none cert list --gossip
+#         $gpg_bin --import -- "${derivative_signing_public_key_item}"
+#         $gpg_bin --check-sigs -- "${derivative_signing_key_fingerprint_item}"
+#         break
+#       fi
+#     done
+#   done
+# }
 
 signed_by_fingerprint() {
-  local fingerprint derivative_signing_key_fingerprint_group derivative_signing_key_fingerprint_item derivative_signing_key_fingerprint_list
+#   local fingerprint derivative_signing_key_fingerprint_group derivative_signing_key_fingerprint_item derivative_signing_key_fingerprint_list
+#
+#   ## TODO: broken since using git_verify_command_wrapper
+#   ##
+#   ## NOTE: Cannot use end-of-options ("--").
+#   ##
+#   ## NOTE: 'tail -n-1' is mandatory, otherwise verifying the fingerprint of a
+#   ## tag will fail.
+#   #fingerprint="$("${git_verify_command_wrapper[@]}" show --no-patch --pretty="format:%GF" "${1}" | tail -n -1)"
+#   fingerprint="$("${git_verify_command_wrapper[@]}" show --no-patch --pretty="format:%GF" "${1}")"
+#
+#   for derivative_signing_key_fingerprint_group in "${derivative_verification_key_fingerprint_group_list[@]}"; do
+#     readarray -t derivative_signing_key_fingerprint_list <<< "${derivative_signing_key_fingerprint_group}"
+#
+#     for derivative_signing_key_fingerprint_item in "${derivative_signing_key_fingerprint_list[@]}"; do
+#       if [ "${fingerprint}" = "${derivative_signing_key_fingerprint_item}" ]; then
+#         true "INFO: fingerprint match, ok."
+#         return 0
+#       fi
+#     done
+#   done
 
-  ## TODO: broken since using git_verify_command_wrapper
-  ##
-  ## NOTE: Cannot use end-of-options ("--").
-  ##
-  ## NOTE: 'tail -n-1' is mandatory, otherwise verifying the fingerprint of a
-  ## tag will fail.
-  #fingerprint="$("${git_verify_command_wrapper[@]}" show --no-patch --pretty="format:%GF" "${1}" | tail -n -1)"
-  fingerprint="$("${git_verify_command_wrapper[@]}" show --no-patch --pretty="format:%GF" "${1}")"
+  command -v sq-git >/dev/null
 
-  for derivative_signing_key_fingerprint_group in "${derivative_verification_key_fingerprint_group_list[@]}"; do
-    readarray -t derivative_signing_key_fingerprint_list <<< "${derivative_signing_key_fingerprint_group}"
-
-    for derivative_signing_key_fingerprint_item in "${derivative_signing_key_fingerprint_list[@]}"; do
-      if [ "${fingerprint}" = "${derivative_signing_key_fingerprint_item}" ]; then
-        true "INFO: fingerprint match, ok."
-        return 0
-      fi
-    done
-  done
+  ## sq-git allows to offload the complexity of OpenPGP signing key import.
+  if sq-git log --policy-file "${sq_git_policy_file}" --trust-root "${sq_git_trust_root}" -- "${1}"; then
+    true "INFO: sq-git verification, ok."
+    return 0
+  fi
 
   1>&2 printf '%s\n' "\
 WARNING: Signing key fingerprint does not match!
 (INFO: If this is intentional, could:
-- A) preferably: add your own signing key, see file 'buildconfig.d/30_signing_key.conf'; or,
+- A) preferably: configure your own sq-git policy file, see file 'buildconfig.d/30_signing_key.conf'; or,
 - B) crude: out-comment this check.)"
   return 1
 }
@@ -119,7 +127,7 @@ verify_ref() {
   esac
 
   ## Policy: All git commits (at least HEAD) is always signed.
-  "${git_verify_command_wrapper[@]}" verify-commit -- "${ref}^{commit}" || return 1
+  #"${git_verify_command_wrapper[@]}" verify-commit -- "${ref}^{commit}" || return 1
   signed_by_fingerprint "${ref}^{commit}" || return 1
 
   if [ "${ref_type}" = 'tag' ]; then
@@ -127,7 +135,7 @@ verify_ref() {
     ##
     ## NOTE: 'refs/tags/' is necessary to prevent ambiguity in the event of a
     ## tag with the same name as a branch or commit.
-    "${git_verify_command_wrapper[@]}" verify-tag -- "refs/tags/${ref}" || return 1
+    #"${git_verify_command_wrapper[@]}" verify-tag -- "refs/tags/${ref}" || return 1
     signed_by_fingerprint "${ref}" || return 1
   fi
 }
