work on support building packages for Ubuntu

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -91,6 +91,9 @@ WHONIX_APT_REPOSITORY_OPTS='--enable --repository testers'
 WHONIX_APT_REPOSITORY_OPTS='--enable --repository developers'
 WHONIX_APT_REPOSITORY_OPTS='--enable --codename jessie'
 
+--release buster|xenial|bionic
+Unsupported.
+
 --report true|false
 true
 false: Default. Skip.
@@ -340,6 +343,16 @@ whonix_build_one_parse_cmd() {
                fi
                export tb_onion
                export whonix_build_sources_clearnet_or_onion
+               shift 2
+               ;;
+           --release)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --release must not be empty.${reset}"
+                  exit 1
+               else
+                  export BUILD_RELEASE="$2"
+                  true "${cyan}BUILD_RELEASE set to $BUILD_RELEASE.${reset}"
+               fi
                shift 2
                ;;
            ## TODO
