build script: New build parameter --tb none|closed|failed. When set to closed, try installing Tor Browser, failing closed. When set to open, fail open. When unset or set to none, don't attempt to install Tor Browser (default).

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -234,6 +234,12 @@ whonix_build_one_script_help() {
 ##
 ## --grmlbin /path/to/grml-debootstrap
 ## Defaults to grml-debootstrap.
+##
+## --tb none|closed|open
+## none: Do not install Tor Browser.
+## closed: Fail closed if Tor Browser cannot be installed.
+## open: Fail closed if Tor Browser cannot and installed.
+## Defaults to none.
 "
 }
 
@@ -586,6 +592,16 @@ whonix_build_one_parse_cmd() {
                      echo "${red}${bold}ERROR: --grmlbin $whonix_build_grml_bin is not executable!${reset}"
                      exit 1
                   fi
+               fi
+               shift 2
+               ;;
+           --tb)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --tb may not be empty.${reset}"
+                  exit 1
+               else
+                  export anon_shared_inst_tb="$2"
+                  true "${cyan}INFO: --tb set to: $anon_shared_inst_tb${reset}"
                fi
                shift 2
                ;;
