fix

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -31,7 +31,7 @@ whonix_build_cmdoptions() {
    ## http://mywiki.wooledge.org/BashFAQ/035
    
    if [ "$*" = "" ]; then
-      true "${red}${bold}ERROR $0${reset}: no option chosen. Use --help." >&2
+      true "${red}${bold}ERROR $0: no option chosen. Use --help.${reset}" >&2
       exit 1
    fi
 
@@ -83,7 +83,7 @@ whonix_build_cmdoptions() {
                break
                ;;
            -*)
-               echo "${red}${bold}ERROR $0:${reset} unknown option: $1" >&2
+               echo "${red}${bold}ERROR $0: unknown option: $1${reset}" >&2
                exit 1
                ;;
            *)
@@ -96,38 +96,38 @@ whonix_build_cmdoptions() {
    ## will remain in the "$@" positional parameters. 
 
    if [ "$WHONIX_BUILD_ALL" = "1" ]; then
-      true "${red}${bold}ERROR $0${reset}: --all not yet implemented. (Help welcome!)" >&2
+      true "${red}${bold}ERROR $0: --all not yet implemented. (Help welcome!)${reset}" >&2
       exit 1         
    fi
    
    if [ ! "$WHONIX_BUILD_INTERNALRUN" = "1" ]; then
       if [ ! "$WHONIX_BUILD_MAIN_SCRIPT_STARTED" = "1" ]; then
          if [ "$WHONIX_BUILD_BUILD" = "1" ] && [ "$WHONIX_BUILD_CLEAN" = "1" ]; then
-            true "${red}${bold}ERROR $0${reset}: You must either use --build or --clean." >&2
+            true "${red}${bold}ERROR $0: You must either use --build or --clean.${reset}" >&2
             exit 1         
          fi
       fi
    fi
    
    if [ "$WHONIX_BUILD_ALL" = "1" ] && [ "$WHONIX_BUILD_GATEWAY" = "1" ]; then
-      true "${red}${bold}ERROR $0${reset}: You can not combine --all with --torgateway. You must either use --all or --torgateway." >&2
+      true "${red}${bold}ERROR $0: You can not combine --all with --torgateway. You must either use --all or --torgateway.${reset}" >&2
       exit 1      
    fi
    
    if [ "$WHONIX_BUILD_ALL" = "1" ] && [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
-      true "${red}${bold}ERROR $0${reset}: You can not combine --all with --torworkstation. You must either use --all or --torworkstation." >&2
+      true "${red}${bold}ERROR $0: You can not combine --all with --torworkstation. You must either use --all or --torworkstation.${reset}" >&2
       exit 1      
    fi
    
    if [ "$WHONIX_BUILD_GATEWAY" = "1" ] && [ "$WHONIX_BUILD_WORKSTATION" = "1" ]; then
-      true "${red}${bold}ERROR $0${reset}: You can not combine --torgateway with --torworkstation. Use --all if that is what you want." >&2
+      true "${red}${bold}ERROR $0: You can not combine --torgateway with --torworkstation. Use --all if that is what you want.${reset}" >&2
       exit 1
    fi
 
    if [ "$WHONIX_BUILD_GATEWAY" = "1" ] || [ "$WHONIX_BUILD_WORKSTATION" = "1" ] || [ "$WHONIX_BUILD_ALL" = "1" ]; then
       true
    else
-      true "${red}${bold}ERROR $0${reset}: You must add --torgateway or --torworkstation or --all."
+      true "${red}${bold}ERROR $0: You must add --torgateway or --torworkstation or --all.${reset}" >&2
       exit 1
    fi
 }
