dracut support
`--initramfs dracut`
`--initramfs initramfs-tools`

https://forums.whonix.org/t/replacing-initramfs-tools-with-dracut/4487

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -168,6 +168,14 @@ linux-headers-686-pae
 linux-headers-amd64
 Possibly others. (Unmaintained!)
 
+--initramfs <Quoted space delimited list of packages.>
+Only of interest for VM builds. Not for installations to root.
+Defaults to dracut.
+none: Do not install initramfs packages.
+dracut
+initramfs-tools
+Possibly others. (Unmaintained!)
+
 --confdir /path/to/config/dir
 Will get sourced after
 \$WHONIX_SOURCE_FOLDER/buildconfig.d /etc/whonix_buildconfig.d ../buildconfig.d
@@ -408,6 +416,19 @@ whonix_build_one_parse_cmd() {
                else
                   export BUILD_HEADER_PKGS="$BUILD_HEADER_PKGS $2"
                   true "${cyan}BUILD_HEADER_PKGS set to $BUILD_HEADER_PKGS.${reset}"
+               fi
+               shift 2
+               ;;
+           --initramfs)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --initramfs must not be empty.${reset}"
+                  exit 1
+               elif [ "$2" = "none" ]; then
+                  export BUILD_INITRAMFS_PKGS="none"
+                  true "${cyan}BUILD_INITRAMFS_PKGS set to $BUILD_INITRAMFS_PKGS.${reset}"
+               else
+                  export BUILD_INITRAMFS_PKGS="$BUILD_INITRAMFS_PKGS $2"
+                  true "${cyan}BUILD_INITRAMFS_PKGS set to $BUILD_INITRAMFS_PKGS.${reset}"
                fi
                shift 2
                ;;
@@ -661,14 +682,18 @@ whonix_build_one_parse_cmd() {
    ## https://forums.whonix.org/t/long-wiki-edits-thread/3477/2009
    [ -n "$target_architecture_pretty_name" ] || target_architecture_pretty_name="Intel_AMD64"
 
+   [ -n "$BUILD_INITRAMFS_PKGS" ] || BUILD_INITRAMFS_PKGS="dracut"
+
    export BUILD_TARGET_ARCH
    export BUILD_KERNEL_PKGS
    export BUILD_HEADER_PKGS
    export target_architecture_pretty_name
+   export BUILD_INITRAMFS_PKGS
 
-   echo "${cyan}INFO: BUILD_TARGET_ARCH    (--arch): $BUILD_TARGET_ARCH${reset}"
-   echo "${cyan}INFO: BUILD_KERNEL_PKGS  (--kernel): $BUILD_KERNEL_PKGS${reset}"
-   echo "${cyan}INFO: BUILD_HEADER_PKGS (--headers): $BUILD_HEADER_PKGS${reset}"
+   echo "${cyan}INFO: BUILD_TARGET_ARCH         (--arch): $BUILD_TARGET_ARCH${reset}"
+   echo "${cyan}INFO: BUILD_KERNEL_PKGS       (--kernel): $BUILD_KERNEL_PKGS${reset}"
+   echo "${cyan}INFO: BUILD_HEADER_PKGS      (--headers): $BUILD_HEADER_PKGS${reset}"
+   echo "${cyan}INFO: BUILD_INITRAMFS_PKGS (--initramfs): $BUILD_INITRAMFS_PKGS${reset}"
 
    if [ "$whonix_build_sources_clearnet_or_onion" = "" ]; then
       echo "${cyan}${bold}INFO: No --connection type 'clearnet' or 'onion' has been chosen. \
