implement `--dry-run`

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -606,6 +606,20 @@ dist_build_one_parse_cmd() {
                export build_remote_derivative_pkgs
                shift 2
                ;;
+           --dry-run)
+               if [ "$2" = "false" ]; then
+                  build_dry_run="false"
+                  true "${cyan}INFO:not  --dry-run${eunder}${reset}"
+               elif [ "$2" = "true" ]; then
+                  build_dry_run="true"
+                  true "${cyan}INFO: ${under}--dry-run${eunder}${reset}"
+               else
+                  echo "${red}${bold}ERROR: supported options for --dry-run are 'true' or 'false'.${reset}"
+                  exit 1
+               fi
+               export build_dry_run
+               shift 2
+               ;;
            --freedom)
                if [ "$2" = "false" ]; then
                   build_freedom_only="false"
