simplify just refreshing deb.torproject.org packages in Whonix repository mirror
https://phabricator.whonix.org/T472

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -661,6 +661,16 @@ whonix_build_one_parse_cmd() {
                whonix_build_pkg_apparmor_only="true"
                shift
                ;;
+           --function)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --function may not be empty.${reset}"
+                  exit 1
+               else
+                  FUNCTION="$2"
+                  true "${cyan}INFO: --function set to $FUNCTION${reset}"
+               fi
+               shift 2
+               ;;
            --)
                shift
                break
