build script: work on cmd line parser https://www.whonix.org/forum/index.php/topic,633.0.html

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -206,6 +206,29 @@ whonix_build_one_script_help() {
 ## --allow-uncommitted false|true
 ## false: Break when uncommitted changes are found. Default.
 ## true: Do not use unless you know what you are doing.
+##
+## --arch
+## Only of interest for VM builds. Not for installations to root.
+## i386: default, best tested.
+## amd64: less tested.
+## kfreebsd-i386: entirely untested and most likely needs work.
+## kfreebsd-amd64: entirely untested and most likely needs work.
+##
+## --kernel <Quoted space delimited list of packages.>
+## Only of interest for VM builds. Not for installations to root.
+## Defaults to linux-image-486 linux-image-686-pae.
+## none
+## linux-image-486
+## linux-image-686-pae
+## linux-image-amd64
+##
+## --headers <Quoted space delimited list of packages.>
+## Only of interest for VM builds. Not for installations to root.
+## Defaults to linux-headers-486 linux-headers-686-pae.
+## none
+## linux-headers-486
+## linux-headers-686-pae
+## linux-headers-amd64
 "
 }
 
@@ -388,30 +411,35 @@ whonix_build_one_parse_cmd() {
                export whonix_build_sources_list="build_sources/debian_testing_frozen.list"
                shift
                ;;
-           --486-linux)
-               export BUILD_TARGET_ARCH="i386"
-               export BUILD_KERNEL_PKGS="$BUILD_KERNEL_PKGS linux-image-486 linux-headers-486"
-               shift
+           --arch)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --arch must not be empty.${reset}"
+                  exit 1
+               else
+                  export BUILD_TARGET_ARCH="$2"
+                  true "${cyan}BUILD_TARGET_ARCH set to $BUILD_TARGET_ARCH.${reset}"
+               fi
+               shift 2
                ;;
-           --32bit-linux)
-               export BUILD_TARGET_ARCH="i386"
-               export BUILD_KERNEL_PKGS="$BUILD_KERNEL_PKGS linux-image-686-pae linux-headers-686-pae"
-               shift
+           --kernel)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --kernel must not be empty.${reset}"
+                  exit 1
+               else
+                  export BUILD_KERNEL_PKGS="$BUILD_KERNEL_PKGS $2"
+                  true "${cyan}BUILD_KERNEL_PKGS set to $BUILD_KERNEL_PKGS.${reset}"
+               fi
+               shift 2
                ;;
-           --64bit-linux)
-               export BUILD_TARGET_ARCH="amd64"
-               export BUILD_KERNEL_PKGS="$BUILD_KERNEL_PKGS linux-image-amd64 linux-headers-amd64"
-               shift
-               ;;
-           --64bit-kfreebsd)
-               echo "${red}${bold}INFO: The parameter --64bit-kfreebsd is entirely untested and most likely needs work.${reset}"
-               export BUILD_TARGET_ARCH="kfreebsd-amd64"
-               shift
-               ;;
-           --32bit-kfreebsd)
-               echo "${red}${bold}INFO: The parameter --32bit-kfreebsd is entirely untested and most likely needs work.${reset}"
-               export BUILD_TARGET_ARCH="kfreebsd-i386"
-               shift
+           --headers)
+               if [ "$2" = "" ]; then
+                  echo "${red}${bold}ERROR: --headers must not be empty.${reset}"
+                  exit 1
+               else
+                  export BUILD_HEADER_PKGS="$BUILD_HEADER_PKGS $2"
+                  true "${cyan}BUILD_HEADER_PKGS set to $BUILD_HEADER_PKGS.${reset}"
+               fi
+               shift 2
                ;;
            --whonix-repo)
                if [ "$2" = "off" ]; then
@@ -524,20 +552,23 @@ whonix_build_one_parse_cmd() {
    done
 
    if [ "$BUILD_KERNEL_PKGS" = "" ]; then
-      echo "${cyan}${bold}INFO: No build target (such as --486-linux, --32bit-linux, \
---64bit-linux, --64bit-kfreebsd [untested] or--32bit-kfreebsd [untested] has been chosen.
-Defaulting to BUILD_TARGET_ARCH ${under}i386${eunder} and setting BUILD_KERNEL_PKGS to:
+      echo "${cyan}${bold}INFO: No --kernel has been chosen. \
+Defaulting BUILD_KERNEL_PKGS to:${reset}
    ${under}linux-image-486${eunder}
+   ${under}linux-image-686-pae${eunder}"
+      export BUILD_KERNEL_PKGS="linux-image-486 linux-image-686-pae"
+   fi
+
+   if [ "$BUILD_HEADER_PKGS" = "" ]; then
+      echo "${cyan}${bold}INFO: No --headers have been chosen. \
+Defaulting BUILD_HEADER_PKGS to:${reset}
    ${under}linux-headers-486${eunder}
-   ${under}linux-image-686-pae${eunder}
-   ${under}linux-headers-686-pae${eunder}${reset}"
-      export BUILD_TARGET_ARCH="i386"
-      export BUILD_KERNEL_PKGS="linux-image-486 linux-headers-486 linux-image-686-pae linux-headers-686-pae"
+   ${under}linux-headers-686-pae${eunder}"
+      export BUILD_HEADER_PKGS="linux-headers-486 linux-headers-686-pae"
    fi
 
    if [ "$BUILD_TARGET_ARCH" = "" ]; then
-      echo "${cyan}${bold}INFO: Apparently environment variable BUILD_KERNEL_PKGS is set, but \
-environment variable BUILD_TARGET_ARCH is not set.
+      echo "${cyan}${bold}INFO: No --arch has been chosen. \
 Defaulting BUILD_TARGET_ARCH to ${under}i386${eunder}.
 (Other possible values would be amd64, kfreebsd-amd64 [untested], kfreebsd-i386 [untested].)${reset}"
       export BUILD_TARGET_ARCH="i386"
