fix

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -481,8 +481,12 @@ whonix_build_one_parse_cmd() {
                if [ "off" = "$2" ]; then
                   true "${cyan}INFO: Not enabling Whonix repository.${reset}"
                else
-                  true "${cyan}INFO: Setting 'WHONIX_APT_REPOSITORY_OPTS' to '$WHONIX_APT_REPOSITORY_OPTS'.${reset}"
                   export WHONIX_APT_REPOSITORY_OPTS="$2"
+                  true "${cyan}INFO: Setting 'WHONIX_APT_REPOSITORY_OPTS' to '$WHONIX_APT_REPOSITORY_OPTS'.${reset}"
+               fi
+               if [ "$WHONIX_APT_REPOSITORY_OPTS" = "" ]; then
+                  echo "${red}${bold}ERROR: '--whonix-repo' may not be empty.${reset}"
+                  exit 1
                fi
                shift 2
                ;;
