CI

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -861,6 +861,20 @@ ${reset}"
          parse_cmd_freedom_versus_nonfreedom_firmware_choice_check
       fi
    fi
+
+   if [ "$CI" = "true" ]; then
+      if ! [ "$dist_build_flavor" = "kicksecure-cli" ]; then
+         ## TODO: cross-building is too slow. Hits GitHub 6 hours maximum time.
+         ## Therefore, build fewer flavors on CI to save build time.
+         ## At this time, build flavor 'kicksecure-cli' only on CI.
+         ## - Specifically cross-builds (using AMD64 to build ARM64) is hitting GitHub CI timeout.
+         ## - It is unlikely that building an LXQt flavor would succeed while the CLI flavor would fail.
+         ## equivalent of '--dry-run true'
+         build_dry_run="true"
+         export build_dry_run
+         true "$BASH_SOURCE INFO: CI=$CI and dist_build_flavor is NOT $dist_build_flavor, therefore setting: build_dry_run=$build_dry_run"
+      fi
+   fi
 }
 
 : "${BASH_SOURCE:=""}"
