implement --freedom true|false
https://www.whonix.org/wiki/Dev/nonfree

diff --git a/help-steps/parse-cmd b/help-steps/parse-cmd
--- a/help-steps/parse-cmd
+++ b/help-steps/parse-cmd
@@ -547,6 +547,20 @@ whonix_build_one_parse_cmd() {
                export whonix_build_redistribute="true"
                shift
                ;;
+           --freedom)
+               if [ "$2" = "false" ]; then
+                  build_freedom_only="false"
+                  true "${cyan}INFO: will include nonfreedom software packages.${reset}"
+               elif [ "$2" = "true" ]; then
+                  build_freedom_only="true"
+                  true "${cyan}INFO: will include Freedom Software packages only.${reset}"
+               else
+                  echo "${red}${bold}ERROR: supported options for --freedom are 'true' or 'false'.${reset}"
+                  exit 1
+               fi
+               export build_freedom_only
+               shift 2
+               ;;
            --function)
                if [ "$2" = "" ]; then
                   echo "${red}${bold}ERROR: --function may not be empty.${reset}"
