fix

diff --git a/help-steps/pre b/help-steps/pre
--- a/help-steps/pre
+++ b/help-steps/pre
@@ -133,7 +133,7 @@ errorhandlerretry() {
    if [ "$retry_last_failed_bash_command_exit_code" = "0" ]; then
       return 0
    else
-      errorhandlerprocessshared "NONE (called by $FUNCNAME)"
+      errorhandlerprocessshared "NONE_(called_by_errorhandlerretry)"
    fi
 }
 
@@ -161,8 +161,8 @@ ${red}${bold}ERROR in ${under}$last_script${eunder} detected!${reset}
 ############################################################
 "
 
-   if [ "$trap_signal_type_last" = "ERR" ]; then
-      true "INFO: Signal trap ERR, considering auto retry..."
+   if [ "$trap_signal_type_last" = "ERR" ] || [ "$trap_signal_type_last" = "NONE_(called_by_errorhandlerretry)" ] ; then
+      true "INFO: Signal trap ERR or called_by_errorhandlerretry, considering auto retry..."
       if [ ! "$whonix_build_auto_retry" = "0" ]; then
          if [ "$whonix_build_auto_retry_counter" = "" ]; then
             whonix_build_auto_retry_counter="1"
@@ -192,28 +192,29 @@ ${red}${bold}ERROR in ${under}$last_script${eunder} detected!${reset}
    fi
    unset whonix_build_auto_retry_counter
 
-   if [ ! "$trap_signal_type_last" = "ERR" ]; then
-      ## TODO: Would otherwise "double" the error handlers.
-      true "INFO: Aborting because of non ERR signal type: $trap_signal_type_last"
-      return 0
-   fi
-
-   true "INFO: whonix_build_non_interactive: $whonix_build_non_interactive | CI: $CI"
-   if [ "$whonix_build_non_interactive" = "true" ] || [ "$CI" = "true" ]; then
-      true "INFO: using non-interactive error handler."
-   else
-      if [ -t "0" ]; then
-         true "INFO: stdin connected to terminal, using interactive error handler."
-         read -p "\
+   answer=""
+   if [ "$trap_signal_type_last" = "ERR" ] || [ "$trap_signal_type_last" = "NONE_(called_by_errorhandlerretry)" ] ; then
+      true "INFO: whonix_build_non_interactive: $whonix_build_non_interactive | CI: $CI"
+      if [ "$whonix_build_non_interactive" = "true" ] || [ "$CI" = "true" ]; then
+         true "INFO: using non-interactive error handler."
+      else
+         if [ -t "0" ]; then
+            true "INFO: stdin connected to terminal, using interactive error handler."
+            read -p "\
 ${red}${bold}ERROR in $0 detected!
 Please have a look above (the block within ###...), note the command that failed, last_failed_exit_code and its output (further above).
 - Please enter c and press enter to ignore the error and continue building. (Recommended against!)
 - Please press r and enter to retry.
 - Please press s and enter to open an chroot interactive shell.
 - Please press enter to cleanup and exit. ${reset}" answer
-      else
-         true "INFO: stdin not connected to terminal, using non-interactive error handler."
+         else
+            true "INFO: stdin not connected to terminal, using non-interactive error handler."
+         fi
       fi
+   else
+      ## TODO: Would otherwise "double" the error handlers.
+      true "INFO: Aborting because of non ERR signal type: $trap_signal_type_last"
+      return 0
    fi
    ignore_error=""
    error_handler_do_retry=""
@@ -239,8 +240,10 @@ fi
 
 errorhandlermaybeexit() {
    if [ "$error_handler_do_retry" = "true" ]; then
-      true "INFO ($FUNCNAME): auto retry succeeded. Will not exit. Continue."
-      return 0
+      if [ "$last_failed_bash_command" = "0" ]; then
+         true "INFO ($FUNCNAME): auto retry succeeded. Will not exit. Continue."
+         return 0
+      fi
    fi
    if [ "$ignore_error" = "true" ]; then
       abort_or_continue="Continue"
