Extracted code for packaging Whonix in debian/rules and made a rules-helper.bsh script, which I can maintain better. Therefore also likely fixed the bug, that /etc/default/grub.whonix wasn't properly displaced.

diff --git a/help-steps/pre b/help-steps/pre
--- a/help-steps/pre
+++ b/help-steps/pre
@@ -75,11 +75,13 @@ error_handler_unmount() {
     back=$'\b'
 } 2>/dev/null ||:
 
-if [ "$(id -u)" != "0" ]; then
-    echo "${red}${bold}ERROR: This must be run as root (sudo)!${reset}"
-    exit 1
-else
-    true "INFO: Script running as root."
+if [ ! "$ROOT_CHECK" = "0" ]; then
+   if [ "$(id -u)" != "0" ]; then
+       echo "${red}${bold}ERROR: This must be run as root (sudo)!${reset}"
+       exit 1
+   else
+       true "INFO: Script running as root."
+   fi
 fi
 
 ## Lower IO priority.
