debugging

diff --git a/help-steps/unmount-helper b/help-steps/unmount-helper
--- a/help-steps/unmount-helper
+++ b/help-steps/unmount-helper
@@ -3,7 +3,7 @@
 ## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
 ## See the file COPYING for copying conditions.
 
-set -x
+#set -x
 set -e
 
 true "INFO: Currently running script: $BASH_SOURCE $@"
@@ -37,16 +37,16 @@ main() {
    sync
 
    ## Debugging.
-   $SUDO_TO_ROOT cat /proc/mounts
-   $SUDO_TO_ROOT dmsetup ls
-   $SUDO_TO_ROOT losetup --all
+   #$SUDO_TO_ROOT cat /proc/mounts
+   #$SUDO_TO_ROOT dmsetup ls
+   #$SUDO_TO_ROOT losetup --all
 
    if ! $SUDO_TO_ROOT cat /proc/mounts | grep "$unmount_folder" ; then
       true "INFO: Not mounted, no need to unmount, ok."
       return 0
    fi
 
-   $SUDO_TO_ROOT umount --verbose --lazy "$unmount_folder" || true "WARNING: umount non-zero exit code."
+   $SUDO_TO_ROOT umount --verbose --lazy "$unmount_folder" || true "INFO: 'umount --verbose --lazy unmount_folder' non-zero exit code."
    sync
    sleep 6
 
@@ -55,20 +55,20 @@ main() {
       return 0
    fi
 
-   $SUDO_TO_ROOT umount --verbose "$unmount_folder" || { exit_code="$?" ; true "WARNING: umount non-zero exit code." ;};
+   $SUDO_TO_ROOT umount --verbose "$unmount_folder" || { exit_code="$?" ; true "INFO: 'umount --verbose $unmount_folder' non-zero exit code." ;};
    sync
    sleep 6
 
-   if ! $SUDO_TO_ROOT cat /proc/mounts | grep "$unmount_folder" ; then
+   if ! $SUDO_TO_ROOT cat /proc/mounts | grep --quiet "$unmount_folder" ; then
       true "INFO: Already unmounted after second attempt using normal mount, ok."
       return 0
    fi
 
-   $SUDO_TO_ROOT umount --verbose --force "$unmount_folder" || { exit_code="$?" ; true "WARNING: umount non-zero exit code." ;};
+   $SUDO_TO_ROOT umount --verbose --force "$unmount_folder" || { exit_code="$?" ; true "INFO: umount '--verbose --force $unmount_folder' non-zero exit code." ;};
    sync
    sleep 6
 
-   if ! $SUDO_TO_ROOT cat /proc/mounts | grep "$unmount_folder" ; then
+   if ! $SUDO_TO_ROOT cat /proc/mounts | grep --quiet "$unmount_folder" ; then
       true "INFO: Already unmounted after third attempt using --force, ok."
       return 0
    fi
@@ -78,9 +78,8 @@ main() {
    ## Debugging.
    $SUDO_TO_ROOT cat /proc/mounts
 
-   ERROR "INFO: Already unmounted after third attempt using --force, ok."
-
-   true
+   echo "ERROR: unmount_folder '$unmount_folder' not unmounted after three attempts!"
+   exit 1
 }
 
 main "$@"
