refactoring

diff --git a/help-steps/unmount-raw b/help-steps/unmount-raw
--- a/help-steps/unmount-raw
+++ b/help-steps/unmount-raw
@@ -56,16 +56,16 @@ unmount_raw() {
    $SUDO_TO_ROOT kpartx -d -s -v "$img"
    sync
 
-   local loop_devices_output loop_devices_list loop_devices_item
+   local loop_devices_output_before loop_devices_list loop_devices_item
    ## Example:
    ## sudo losetup --associated /home/user/derivative-binary/17.4.0.2/Kicksecure-CLI-17.4.0.2.Intel_AMD64.raw --noheadings --output NAME
    #/dev/loop1
    #/dev/loop2
    #/dev/loop0
    ## NOTE: There should only be one loop device (such as '/dev/loop1'). But in case of bugs, there might be multiple.
-   loop_devices_output="$($SUDO_TO_ROOT losetup --associated "$img" --noheadings --output NAME)"
+   loop_devices_output_before="$($SUDO_TO_ROOT losetup --associated "$img" --noheadings --output NAME)"
 
-   mapfile -t loop_devices_list <<< "$loop_devices_output"
+   mapfile -t loop_devices_list <<< "$loop_devices_output_before"
 
    for loop_devices_item in "${loop_devices_list[@]}" ; do
       ## Check if the block device still exists.
@@ -73,7 +73,17 @@ unmount_raw() {
          true "INFO: kpartx -d -s -v failed to unmount all loop devices, attempting to unmount..."
          ## Inside docker (and maybe other corner cases) 'kpartx -d -s -v "$img"' might fail to unmount loop devices.
          ## https://forums.whonix.org/t/docker-container-that-builds-whonix-images/17494/43
-         $SUDO_TO_ROOT kpartx -d -s -v "$loop_devices_item"
+
+         ## Overwrite with '|| true' because it might exit non-zero.
+         ## sudo kpartx -d -s -v /dev/loop0
+         #del devmap : loop0p1
+         #del devmap : loop0p2
+         #loop0p3 is in use. Not removing
+         #zsh: exit 1
+         $SUDO_TO_ROOT kpartx -d -s -v "$img" || true "INFO: kpartx non-zero exit code."
+
+         ## Overwrite with '|| true' because: Precaution. Testing. Unknown is strictly required.
+         $SUDO_TO_ROOT losetup -d "$loop_devices_item" || true "INFO: losetup non-zero exit code."
       fi
    done
 
