refactoring

diff --git a/help-steps/variables b/help-steps/variables
--- a/help-steps/variables
+++ b/help-steps/variables
@@ -167,6 +167,21 @@ if [ "$dist_build_redistributable" = "true" ]; then
    export anon_shared_inst_tb
 fi
 
+## repository-dist-initializer
+repository_dist_initializer_setup() {
+   [ -n "${binary_build_folder_dist}" ] || error "repository_dist_initializer_setup: variable binary_build_folder_dist missing!"
+   [ -n "${CHROOT_FOLDER}" ] || error "repository_dist_initializer_setup: variable CHROOT_FOLDER missing!"
+
+   ## Enable generation of repository-dist config file
+   if [ "${build_remote_repo_enable}" = 'true' ]; then
+      echo "${DERIVATIVE_APT_REPOSITORY_OPTS}" | sponge -- "${binary_build_folder_dist}/derivative_apt_repository_opts"
+      mkdir --parents "${CHROOT_FOLDER}/var/lib/repository-dist/"
+      $SUDO_TO_ROOT cp "${binary_build_folder_dist}/derivative_apt_repository_opts" "${CHROOT_FOLDER}/var/lib/repository-dist/derivative_apt_repository_opts"
+   else
+      safe-rm -f "${binary_build_folder_dist}/derivative_apt_repository_opts"
+   fi
+}
+
 export dist_build_sources_list_primary
 
 ## https://forums.whonix.org/t/kicksecure-etc-hostname-etc-hosts/10919
