sanity test

diff --git a/help-steps/variables b/help-steps/variables
--- a/help-steps/variables
+++ b/help-steps/variables
@@ -683,6 +683,13 @@ set_default_variable libvirt_target_network_file_internal "${dist_binary_build_f
 set_default_variable copy_vms_into_raw_file_one "${dist_binary_build_folder}/Whonix-Gateway-${dist_build_desktop}-${dist_build_version}.qcow2"
 set_default_variable copy_vms_into_raw_file_two "${dist_binary_build_folder}/Whonix-Workstation-${dist_build_desktop}-${dist_build_version}.qcow2"
 
+## Sanity test. dm-prepare-release uses 'rm -r'.
+## XXX: hardcoded derivative-binary
+if ! echo "$dist_binary_build_folder" | grep --quiet --fixed-strings -- "derivative-binary" ; then
+   echo "$0: FAIL: wrong folder: dist_binary_build_folder: $dist_binary_build_folder"
+   exit 1
+fi
+
 mkdir --parents "${dist_binary_build_folder}"
 
 ## {{{
