control port filter proxy improvements

diff --git a/whonix_gateway/usr/bin/controlportfilt b/whonix_gateway/usr/bin/controlportfilt
--- a/whonix_gateway/usr/bin/controlportfilt
+++ b/whonix_gateway/usr/bin/controlportfilt
@@ -6,6 +6,57 @@
 
 set -x
 
+ID="$(uuidgen -r)"
+LOG="/var/log/controlportfilt"
+OWN_PID="$$"
+
+echo "$ID $0 INFO: Starting... pid: "$OWN_PID"" >> "$LOG"
+
+echo "$OWN_PID" > "/var/run/controlportfilt/own_pid"
+rm --force "/var/run/controlportfilt/error"
+
+error_handler() {
+   local return_code="$?"
+   local bash_command="$BASH_COMMAND"
+   if [ "$ID" = "" ] ; then
+      ID="No_ID"
+   fi
+   echo "$ID $0 ERROR: return_code: $return_code | bash_command: $bash_command" >> "$LOG"
+
+   /sbin/start-stop-daemon \
+      --stop \
+      --quiet \
+      --pidfile "/var/run/controlportfilt/tcpserver_pid" \
+      --signal 2 \
+      --retry 2
+   
+   touch "/var/run/controlportfilt/error"
+   rm --force "/var/run/controlportfilt/ownrunning"
+   rm --force "/var/run/controlportfilt/tcpserver_pid"
+   rm --force "/var/run/controlportfilt/own_pid"
+   exit 1
+}
+
+trap "error_handler" ERR
+
+trap_sigint() {
+   echo "$ID $0 INFO: SIGINT received. Exiting." > "$LOG"
+   
+   /sbin/start-stop-daemon \
+      --stop \
+      --quiet \
+      --pidfile "/var/run/controlportfilt/tcpserver_pid" \
+      --signal 2 \
+      --retry 2
+   
+   rm --force "/var/run/controlportfilt/ownrunning"
+   rm --force "/var/run/controlportfilt/tcpserver_pid"
+   rm --force "/var/run/controlportfilt/own_pid"
+   exit 0
+}
+
+trap "trap_sigint" SIGINT
+
 tcpserver \
    -v \
    -1 \
@@ -13,5 +64,27 @@ tcpserver \
    -H \
    0 \
    9052 \
-   /bin/bash -x -c /usr/lib/whonix/cpf-tcpserver
+   /bin/bash -x -c /usr/lib/whonix/cpf-tcpserver &
 
+tcpserver_pid="$!"
+
+echo "$ID $0 INFO: Started. tcpserver_pid: "$tcpserver_pid" Waiting for connections..." >> "$LOG"
+
+touch "/var/run/controlportfilt/ownrunning"
+
+echo "$tcpserver_pid" > "/var/run/controlportfilt/tcpserver_pid"
+
+tcpserver_return="0"
+wait "$tcpserver_pid" || { tcpserver_return="$?" ; true; };
+
+rm --force "/var/run/controlportfilt/ownrunning"
+rm --force "/var/run/controlportfilt/tcpserver_pid"
+rm --force "/var/run/controlportfilt/own_pid"
+
+if [ "$tcpserver_return" = "0" ]; then
+   echo "$ID $0 INFO: End with exit code (0): "$tcpserver_return"" >> "$LOG"
+   exit "0"
+else
+   echo "$ID $0 ERROR: End with exit code (x): "$tcpserver_return"" >> "$LOG"
+   exit "$tcpserver_return"
+fi
diff --git a/whonix_gateway/usr/lib/whonix/cpf-tcpserver b/whonix_gateway/usr/lib/whonix/cpf-tcpserver
--- a/whonix_gateway/usr/lib/whonix/cpf-tcpserver
+++ b/whonix_gateway/usr/lib/whonix/cpf-tcpserver
@@ -6,17 +6,29 @@
 
 set -x
 
+LOG="/var/log/controlportfilt"
+
 error_handler() {
    local return_code="$?"
    local bash_command="$BASH_COMMAND"
    if [ "$ID" = "" ] ; then
       ID="No_ID"
    fi
-   echo "$ID ERROR: return_code: $return_code | bash_command: $bash_command" >> /var/log/controlportfilt
+   echo "$ID ERROR: return_code: $return_code | bash_command: $bash_command" >> "$LOG"
    exit 1
 }
 
 trap error_handler ERR
+
+trap_sigint() {
+   if [ "$ID" = "" ] ; then
+      ID="No_ID"
+   fi
+   echo "$ID INFO: SIGINT received. Exiting." > "$LOG"
+   exit 0
+}
+
+trap "trap_sigint" SIGINT
 
 OIFS="$IFS"
 IFS="$OIFS"
@@ -26,7 +38,9 @@ IFS="$OIFS"
 
 ID="$(uuidgen -r)"
 
-echo "$ID INFO: Getting connection... " >> /var/log/controlportfilt
+cpf_pid="$$"
+
+echo "$ID INFO: Getting connection... cpf_pid: "$cpf_pid"" >> "$LOG"
 
 ## {{{ /etc/controlportfilt.d
 
@@ -48,7 +62,7 @@ if [ -d /etc/controlportfilt.d ]; then
       fi
    done
 else
-   echo "$0 ERROR: configuration folder /etc/controlportfilt.d does not exist."
+   echo "$ID ERROR: configuration folder /etc/controlportfilt.d does not exist."
    exit 1
 fi
 
@@ -71,13 +85,13 @@ done
 write_back() {
    IFS="$OIFS"
    printf "${1+"$@"}\r\n"
-   echo "$ID BACK: ${1+"$@"}" >> /var/log/controlportfilt
+   echo "$ID BACK: ${1+"$@"}" >> "$LOG"
 }
 
 received() {
    IFS="$OIFS"
    true "${1+"$@"}"
-   echo "$ID GOT: ${1+"$@"}" >> /var/log/controlportfilt
+   echo "$ID GOT: ${1+"$@"}" >> "$LOG"
 }
 
 while read -r; do
@@ -146,16 +160,18 @@ while read -r; do
    fi   
 
    tor_ctrl_return="0"
-   var="$(tor-ctrl -v -s 0 -P 9051 -a /var/run/tor/control.authcookie -c "$cleaned_reply")" || { tor_ctrl_return="$?" ; true; }
+   var="$(tor-ctrl -v -s 0 -P 9051 -a /var/run/tor/control.authcookie -c "$cleaned_reply")" &
+   wait "$!" || { tor_ctrl_return="$?" ; true; }
    
    if [ ! "$tor_ctrl_return" = "0" ]; then
-      echo "$ID ERROR: tor-ctrl returned a non-zero exit code: "$tor_ctrl_return". var: "$var" | Let's try again..." >> /var/log/controlportfilt
+      echo "$ID ERROR: tor-ctrl returned a non-zero exit code: "$tor_ctrl_return". var: "$var" | Let's try again..." >> "$LOG"
       
       tor_ctrl_return="0"
-      var="$(tor-ctrl -v -s 0 -P 9051 -a /var/run/tor/control.authcookie -c "$cleaned_reply")" || { tor_ctrl_return="$?" ; true; }
+      var="$(tor-ctrl -v -s 0 -P 9051 -a /var/run/tor/control.authcookie -c "$cleaned_reply")" &
+      wait "$!" || { tor_ctrl_return="$?" ; true; }
       
       if [ ! "$tor_ctrl_return" = "0" ]; then
-         echo "$ID ERROR: tor-ctrl returned again a non-zero exit code: "$tor_ctrl_return". var: "$var" | Breaking." >> /var/log/controlportfilt
+         echo "$ID ERROR: tor-ctrl returned again a non-zero exit code: "$tor_ctrl_return". var: "$var" | Breaking." >> "$LOG"
          break
       fi
    fi
@@ -204,4 +220,4 @@ done
 
 IFS="$OIFS"
 
-echo "$ID INFO: End. " >> /var/log/controlportfilt
+echo "$ID INFO: End. " >> "$LOG"
