refactoring: return_code -> exit_code

diff --git a/whonix_gateway/usr/bin/controlportfilt b/whonix_gateway/usr/bin/controlportfilt
--- a/whonix_gateway/usr/bin/controlportfilt
+++ b/whonix_gateway/usr/bin/controlportfilt
@@ -17,12 +17,12 @@ echo "$OWN_PID" > "/var/run/controlportfilt/own_pid"
 rm --force "/var/run/controlportfilt/error"
 
 error_handler() {
-   local return_code="$?"
+   local exit_code="$?"
    local bash_command="$BASH_COMMAND"
    if [ "$ID" = "" ] ; then
       ID="No_ID"
    fi
-   echo "$ID $0 ERROR: return_code: $return_code | bash_command: $bash_command" >> "$LOG"
+   echo "$ID $0 ERROR: exit_code: $exit_code | bash_command: $bash_command" >> "$LOG"
 
    /sbin/start-stop-daemon \
       --stop \
diff --git a/whonix_gateway/usr/lib/whonix/cpf-tcpserver b/whonix_gateway/usr/lib/whonix/cpf-tcpserver
--- a/whonix_gateway/usr/lib/whonix/cpf-tcpserver
+++ b/whonix_gateway/usr/lib/whonix/cpf-tcpserver
@@ -10,12 +10,12 @@ set -o pipefail
 LOG="/var/log/controlportfilt.log"
 
 error_handler() {
-   local return_code="$?"
+   local exit_code="$?"
    local bash_command="$BASH_COMMAND"
    if [ "$ID" = "" ] ; then
       ID="No_ID"
    fi
-   echo "$ID ERROR: return_code: $return_code | bash_command: $bash_command" >> "$LOG"
+   echo "$ID ERROR: exit_code: $exit_code | bash_command: $bash_command" >> "$LOG"
    exit 1
 }
 
diff --git a/whonix_shared/usr/lib/whonix/msgprogressbar b/whonix_shared/usr/lib/whonix/msgprogressbar
--- a/whonix_shared/usr/lib/whonix/msgprogressbar
+++ b/whonix_shared/usr/lib/whonix/msgprogressbar
@@ -13,7 +13,7 @@ set -o pipefail
 scriptname="$(basename $0)"
 
 error_handler() {
-   local return_code="$?"
+   local exit_code="$?"
 
    local msg="\
 ###############################################################################
@@ -24,12 +24,12 @@ error_handler() {
 ## Please report this bug!
 ##
 ## BASH_COMMAND: $BASH_COMMAND
-## return_code: $return_code
+## exit_code: $exit_code
 ###############################################################################\
 "
    echo "$msg"
    mkdir --parents ~/".whonix"
-   echo "$scriptname: BASH_COMMAND: $BASH_COMMAND | return_code: $return_code" > ~/".whonix/msgdispatcher-error.log"
+   echo "$scriptname: BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code" > ~/".whonix/msgdispatcher-error.log"
    exit 1
 }
 
diff --git a/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks b/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
--- a/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
+++ b/whonix_shared/usr/share/whonix/chroot-scripts-pre.d/20_sanity_checks
@@ -58,11 +58,11 @@ command -v debsums >/dev/null
 
 true "INFO: Trying to find out if there are packages (or debs) which do not have an MD5 sums file..."
 
-return_code="0"
-debsums_return1="$(debsums --list-missing 2>&1)" || { return_code="$?" ; true; };
+exit_code="0"
+debsums_return1="$(debsums --list-missing 2>&1)" || { exit_code="$?" ; true; };
 
-if [ ! "$return_code" = "0" ]; then
-   error "ERROR: debsums returned a non-zero return_code: $return_code!"
+if [ ! "$exit_code" = "0" ]; then
+   error "ERROR: debsums returned a non-zero exit_code: $exit_code!"
 fi
 
 if [ "$debsums_return1" = "" ]; then
@@ -77,11 +77,11 @@ fi
 
 true "INFO: Trying to find out if there are any packages (or debs) with missing files..."
 
-return_code="0"
-debsums_return2="$(debsums --silent 2>&1)" || { return_code="$?" ; true; };
+exit_code="0"
+debsums_return2="$(debsums --silent 2>&1)" || { exit_code="$?" ; true; };
 
-if [ ! "$return_code" = "0" ]; then
-   error "ERROR: debsums returned a non-zero return_code: $return_code!"
+if [ ! "$exit_code" = "0" ]; then
+   error "ERROR: debsums returned a non-zero exit_code: $exit_code!"
 fi
 
 if [ "$debsums_return2" = "" ]; then
@@ -100,7 +100,7 @@ true "      (Has to be reviewed manually by the builder.)"
 true "      (A differencing /etc/resolv.conf.whonix is expected when building \
 Virtual Machine images, because the /etc/resolv.conf from the host has been mounted inside the image.)"
 
-return_code="0"
-debsums_return3="$(debsums --config --silent 2>&1)" || { return_code="$?" ; true; };
+exit_code="0"
+debsums_return3="$(debsums --config --silent 2>&1)" || { exit_code="$?" ; true; };
 
 true "INFO: Listed changed configuration files."
